### ISSUE TITLE
[Request] Support all parameters for Runtime customizations

### ISSUE THREAD

**Issue by yukihira1992** [CircleCI-Public/slack-orb#100]
I want to  support all parameters in addition to the `channel` parameter of incoming webhook. #67

- `username`
- `icon_emoji`
- `icon_url`

https://api.slack.com/custom-integrations/incoming-webhooks

**Comment by KyleTryon** [comment]
I just discovered this note on slack's docs that may warrant further research:

https://api.slack.com/incoming-webhooks

> You cannot override the default channel (chosen by the user who installed your app), username, or icon when you're using Incoming Webhooks to post messages. Instead, these values will always inherit from the associated Slack app configuration.
