### ISSUE TITLE
channel parameter is not described correctly.

### ISSUE THREAD

**Issue by MrAfrazKhan** [CircleCI-Public/slack-orb#105]
### Orb version
2.1

### What happened

Description of **channel parameter** is very vague as it may confuse user between **Channel Name & Channel Id**. 'channel settings' in description indicates that channel is some sort of an object which i think is not sufficient to let the user know about correct convention of channel parameter.
### Expected behavior
There must be concise distinction about **channel parameter** whether it is **Channel ID or Channel Name**. i think it is Channel ID as explained in _src/examples/notify.yml_. So there must be proper description for channel parameter in each file of repo.

**Comment by KyleTryon** [comment]
Merged #106
