### ISSUE TITLE
Add Then Replace Executor

### ISSUE THREAD

**Issue by felicianotech** [CircleCI-Public/slack-orb#128]
This orb includes a single executor called `alpine`. It uses the Docker image`cibuilds/base`, which is one of my Alpine-based images from my `cibuilds` project. We now have a suitable replacement, `cimg/base`.

According to our [Orbs Best Practices](https://circleci.com/docs/2.0/orbs-best-practices/#executors), we should have a default executor names `executor`, which this orb currently does not.

The route I see forward here is:

- [ ] PR #129 - add a `default` executor that contains the `cimg/base` image
- [ ] PR #130 - remove the `alpine` executor in the future

**Comment by KyleTryon** [comment]
Note: Ensure the `stable` tag is used.

**Comment by dsayling** [comment]
To be fixed in v4. Leaving open until addressed.
