### ISSUE TITLE
[request] add a `success_only` parameter to `status` command

### ISSUE THREAD

**Issue by blordpluto** [CircleCI-Public/slack-orb#133]
Hi guys,

Our use case is that we are doing multiple flavored deploys from a single repo. If there is a build or deploy failure, we want to message a Slack channel for the devs to fix it. `fail_only` works for that. Devs don't need to be bothered if there is no error. Great.

But if there is a successful deploy, we want to notify the testing and reliability people, in a different channel. BUT the testers don't care about failures. They only want to know when something new has successfully been deployed. And there is a lot of volume so controlling noise is important.

I have glanced at the source and honestly I could probably edit it in myself in about 5 minutes. Just an if statement with an early return, following the current pattern. But I am loathe to fork this and get into the orb business, and I suspect that there will be others out there who will need this feature just as much as I do. So I want to approach you first about getting a `success_only` parameter baked into your standard orb.

Or if there is an easy workaround I would love to know!

Thanks in advance for any help.

**Comment by blordpluto** [comment]
Hi, can you please respond? For reference, I have created a branch [here](https://github.com/blordpluto/slack-orb/tree/success-only). Would like to submit a PR.

**Comment by KyleTryon** [comment]
Changes requested on PR.
