### ISSUE TITLE
[Request] enable sending slack/status using container without bash installed

### ISSUE THREAD

**Issue by jsugarman** [CircleCI-Public/slack-orb#134]
### Orb version
slack: circleci/slack@3.4.1

### What happened
I am using circleCI to run a smoke test within a prebuilt container (a rails app). The container
is based on Alpine but is also run as a non-root user (by design). Bash is not available and 
the image, deliberately prevents further installation (i.e.`apk update && apk add bash` not permitted).

#### Relates to
 https://github.com/CircleCI-Public/slack-orb/issues/66

### Expected behaviour

It would be great if it worked with whatever shell, but particularly the standard Alpine POSIX shell

**Comment by timothyclarke** [comment]
@jsugarman  The 4.0 version of the orb can run on alpine (so long as curl and jq is installed)
