### ISSUE TITLE
[Question] Is it possible to send markdown messages

### ISSUE THREAD

**Issue by hassenius** [CircleCI-Public/slack-orb#136]
Slack supports both "standard" text as well as markdown message type for richer messages.
Using markdown to format the messages can be quite powerful, particularly using things like codeblocks, but especially handling the "```" characters for text that is parsed and passed around is quite complex.
1. Is it possible to use markdown by default in the slack orb
2. Are there any examples available to save loads of folks experimentation time?

Thanks

**Comment by emma-sax4** [comment]
In my experience, *some* markdown formatting works, but not all. All of this, I had to test out and experiment with. At the end of the day, that's what you'll have to do as well to get your Slack messages formatted properly.

### Bold
```
Deploy to GitHub Pages was *successful*
```
correctly renders as:
> Deploy to GitHub Pages was **successful**

---

```
Build #$CIRCLE_BUILD_NUM of $CIRCLE_PROJECT_REPONAME@*$CIRCLE_BRANCH*
```
does not correctly render:
> Build #224 of repo_name@\*branch_name\*

---

```
Build #$CIRCLE_BUILD_NUM of $CIRCLE_PROJECT_REPONAME@ *$CIRCLE_BRANCH*
```
correctly renders (but with a space):
> Build #224 of repo_name@ **branch_name**

---

```
Build #$CIRCLE_BUILD_NUM of $CIRCLE_PROJECT_REPONAME@ \*$CIRCLE_BRANCH\*
```
does not correctly render (Slack returns `invalid_payload` response).

### Inline code
```
Build #$CIRCLE_BUILD_NUM of $CIRCLE_PROJECT_REPONAME@ `$CIRCLE_BRANCH`
```
does not correctly render:
> Build #224 of repo_name@
---
```
Build #$CIRCLE_BUILD_NUM of $CIRCLE_PROJECT_REPONAME@ \`$CIRCLE_BRANCH\`
```
correctly renders (but with a space):
Build #224 of repo_name@ `branch_name`

### Italics
```
Deploy to GitHub Pages was _successful_
```
correctly renders as:
> Deploy to GitHub Pages was _successful_

---

```
Build #$CIRCLE_BUILD_NUM of $CIRCLE_PROJECT_REPONAME@ _$(CIRCLE_BRANCH)_
```
does not correctly render:
> Build #224 of repo_name@ __
---

```
Build #$CIRCLE_BUILD_NUM of $CIRCLE_PROJECT_REPONAME@ \_$CIRCLE_BRANCH\_
```
does not correctly render (Slack returns `invalid_payload` response).

### Other

You can also do newlines:
```
- slack/status:
    success_message: "Build *passed*.\n#$CIRCLE_BUILD_NUM."
```
renders as
> Build **passed**.
> #224

---

And you can do hyperlinks:
```
Build <$CIRCLE_BUILD_URL|#$CIRCLE_BUILD_NUM> of $CIRCLE_PROJECT_REPONAME@$CIRCLE_BRANCH
```
renders as
> Build [#224](https://example.com) of repo_name@branch_name

**Comment by KyleTryon** [comment]
Thank you @emma-sax4
