### ISSUE TITLE
slack orb doesn't work with circleci local execute

### ISSUE THREAD

**Issue by bark-frank** [CircleCI-Public/slack-orb#144]
### Orb version

@3.4.2

### What happened

When running:

    circleci config process .circleci/config.yml > process.yml

I get the error:

    Error: 
    Configuration errors: 1 error occurred:

    * In step 2 definition: step type "slack/status" is not a valid type

Do orbs in general work locally?  If not, how would I get it to work?  Thanks!

### Sample code

    version: 2.2

    orbs:
      slack: circleci/slack@3.4.2

    jobs:
      name_of_my_job:
        docker:
          - image: circleci/any # doesn't matter which
        steps:
          - run:  exit 0
          - slack/status:
              fail_only: true
              command: |
                echo works

**Comment by KyleTryon** [comment]
Hello @bark-frank this issue would be better suited for the CLI repo: https://github.com/CircleCI-Public/circleci-cli

However, I can confirm if you process configs down to version 2.0 using the CLI as you have this should work.

I notice you have version "2.2" listed, I am not sure what kind of errors this could cause but the current config version only goes to "2.1". I have a feeling if the version specified is unknown, it will default to 2.0 which would cause the issue you describe. 

If this issue continues please contact our support team directly or open an issue on the CLI if you believe there is a bug.

Thank you and good luck!
