### ISSUE TITLE
New Release?

### ISSUE THREAD

**Issue by scottrobertson** [CircleCI-Public/slack-orb#146]
Hey

When will the next release go out? I need access to the success_only flag

**Comment by DevBOFH** [comment]
Just following up on the above comment. Any reason there hasn't been a release cut with the success_only flag available?

**Comment by KyleTryon** [comment]
Hello Folks.

A major version change is coming which addresses this and more. We will open a draft PR shortly for comment. Please feel free to take a look here: https://github.com/CircleCI-Public/slack-orb/tree/Major-block-kit-redesign

We will soon be looking for beta testers and would love your early feedback.

To add to this, as the Slack Orb was one of our first orbs, the development pipeline is currently a little fragile. This new branch above includes an entirely new production pipeline with true testing. This will greatly increase the speed of future releases.

**Comment by KyleTryon** [comment]
Update, Release on the Slack orb 4.0.0 is about 2 weeks out.
