### ISSUE TITLE
only_for_branches filter not working in notify-on-failure

### ISSUE THREAD

**Issue by CloudySnake** [CircleCI-Public/slack-orb#149]
### Orb version
3.4.2

### What happened
I am trying to limit failure notifications to test and master branches only.  I'm using the following job syntax
`- slack/notify-on-failure:
        only_for_branches: "test,master"`
edit - can't get my code to format properly here but the only_for_branches is on the next line and indented correctly

When I force a failure on a feature branch I still get a slack alert informing me of the error.

### Expected behavior
I would expect this to limit the failure alerts just to test and master.  I have tried a number of different ways to input the string (single quote, double quote, no quotes, spaces, no spaces) but I get the same behaviour each time.

**Comment by CloudySnake** [comment]
I got this working.  In order for it to work I had to add my Slack Webhook with the new UI not the old UI (myself and my colleagues seem to be flipped between the two depending on how CircleCI is feeling).

**Comment by C-Saunders** [comment]
I am having this same issue - notifications for failures on any branch.

My config is nearly identical to what you described:
```yaml
version: 2.1

slack/notify-on-failure:
  only_for_branches: "master,stable"

orbs:
  slack: circleci/slack@3.4.2
```

I added the webhook using the Slack Integrations panel (within Project Settings) using the new UI.

**Comment by CloudySnake** [comment]
Worth trying without the quotes around the string,  that is working for me (though it could be coincidence).  I would also check the pipeline logs for the stage that is issuing this alert, you should be able to see the script fire as there's a number of statuses it prints out.

**Comment by C-Saunders** [comment]
Thanks for your reply! I originally had no quotes, so I added them before posting here, but it didn't change the behavior.

My current theory is that the issue is that I have this at the top level of the yaml file (as shown in my example), rather than as a step/the last step in a job. I don't see logs from this anywhere, and I'm not sure where I'd look since the UI is totally step-based.

**Comment by CloudySnake** [comment]
Yes you need to add it as part of the jobs (Circle really don't believe in DRY). I create a command (below) that I add to the relevant steps I want to alert if they fail (which is largely all of them). I don't know if this helps at all?

`commands:
  slack_notify_on_failure:
    steps:
      - slack/notify-on-failure:
          only_for_branches: master,test`
