### ISSUE TITLE
Proposal: To allow a custom action (button) on messages

### ISSUE THREAD

**Issue by rodrigodiez** [CircleCI-Public/slack-orb#150]
# Proposing
To have the possibility of adding custom actions - buttons - to notifications by adding 2 new parameters:

- `custom_action_text`: `string` defaults to `""`
- `custom_action_url`: `string` defaults to `""`

If both parameters are set, the API call to Slack would include an extra action

# Use cases
- To provide an easy and UI appealing way of visiting a recently deployed application
- To provide an easy an UI appealing way of visiting the SonarCloud report of a finished build

Happy to provide with a PR if you are happy to see this implemented

Thanks for your work!

**Comment by gmemstr** [comment]
@rodrigodiez Curious if you've taken a look at the work we're doing in this branch: https://github.com/CircleCI-Public/slack-orb/tree/Major-block-kit-redesign. This may address your needs.
