### ISSUE TITLE
False Failure -> Passing steps & yet Orb Reports failure 

### ISSUE THREAD

**Issue by cappetta** [CircleCI-Public/slack-orb#155]
### Orb version

  slack: circleci/slack@3.4.2

### What happened
All 3 parts of the workflow are passing, yet orb is reporting a failure?
![ORB-failure-msg](https://user-images.githubusercontent.com/5652156/86315817-38a7e700-bbf9-11ea-988e-4ea2eae241f3.png)

![circle-ci-passing-2](https://user-images.githubusercontent.com/5652156/86315823-3f365e80-bbf9-11ea-9e67-6431c80045b6.png)

https://app.circleci.com/pipelines/github/cappetta/CyberRange/353/workflows/b5e7d86b-fa38-4af2-9f8c-51353d335194

CircleCI config file: https://github.com/cappetta/CyberRange/blob/master/.circleci/config.yml

### Expected behavior

This should be posting as success

### Other notes:

I've simplified my circleci config file to be a basic test with commit, still failing...

![slackorb-status](https://user-images.githubusercontent.com/5652156/86403918-a47f6380-bc7c-11ea-9c54-63b9e2423fee.png)

Yet CircleCi is all green.  Not sure why this varies across multiple products.  I also notice the compare url environmental variable is filled out yet posting in slack as empty.  that's a different 3rd party orb bug.  Do tell if this orb contains that feature.

 
![circleci-job-all-green](https://user-images.githubusercontent.com/5652156/86405261-1193f880-bc7f-11ea-8a0c-63b8aef173f1.png)

**Comment by cappetta** [comment]
Note - I have another project using this orb and working without issue.  Both have passing pipelines/steps/workflows yet this one does not report back with success.  investigating and trying to figure out what is causing the issue...

**Comment by gmemstr** [comment]
@cappetta Curious if you are still experiencing this issue - the linked job appears to be posting the correct data, which is very odd if the message being displayed in Slack is incorrect.

**Comment by cappetta** [comment]
@gmemstr - still seeing it 👎 

![image](https://user-images.githubusercontent.com/5652156/91314494-a0eff080-e784-11ea-8ed8-2113bce7ed33.png)

**Comment by gmemstr** [comment]
@cappetta We recently released version 4 of this orb, which is a major overhaul of the functionality and behaviour. Would you mind giving it a try and seeing if this issue persists?
