### ISSUE TITLE
Step does not fail when Slack or curl returns error

### ISSUE THREAD

**Issue by teka23** [CircleCI-Public/slack-orb#157]
### Orb version

any

### What happened

The step does not immediately exit when there is an error. 

### Expected behaviour

When curl returns an error it should immediately exit. It should also fail when Slack response is not 200.

What do you think?

**Comment by gmemstr** [comment]
@teka23 Would you mind elaborating a little further? As far as I can tell, the expected behaviour is the current behaviour, as the curl command has final say in the exit code of the command/job in orb versions <4.

**Comment by KyleTryon** [comment]
This has purposefully been designed to _not_ error in the event a slack event does not fire. This was a decision that a slack notification should not affect your pipeline. Open to thoughts. The next version of the orb does not currently have this same design and would fail.
