### ISSUE TITLE
shell verification shouldn't be based on $SHELL

### ISSUE THREAD

**Issue by CaptainPatate** [CircleCI-Public/slack-orb#16]
Depending on the Docker image we use, this orb can fail even if `bash` is installed.
For example with a Docker image like this:
```Dockerfile
FROM alpine:3.7

RUN apk --no-cache add bash\
                       ca-certificates\
                       make

WORKDIR /app

ENTRYPOINT ["make"]
```

```shell
docker run --rm -it --entrypoint /bin/sh captainpatate/make-dnscontrol:v0.2.7 
/app # echo $SHELL

/app # echo $BASH

```
```shell
docker run --rm -it --entrypoint /bin/bash captainpatate/make-dnscontrol:v0.2.7 
bash-4.4# echo $SHELL
/bin/ash
bash-4.4# echo $BASH
/bin/bash
```

Even if we use `bash`, I guess some Docker entrypoint trick makes `$SHELL` report the login shell instead of the real shell. It would be better to use the presence of the variable `$BASH` to verify that we are indeed inside a Bash shell.

**Comment by zzak** [comment]
Hello @CaptainPatate,

Thanks for your report.

It seems that bash reserves the environment variable `$BASH` for this reason (inside bash):
http://tldp.org/LDP/Bash-Beginners-Guide/html/sect_03_02.html#sect_03_02_04_02

I'm wondering though if we can rely on it?

Would you be willing to send a patch to replace the shell check?

**Comment by CaptainPatate** [comment]
Yes sure, I'll try it next week and make a PR if it works.
