### ISSUE TITLE
Support multiple webhook URLs for different channels as environment variables

### ISSUE THREAD

**Issue by alecwcp** [CircleCI-Public/slack-orb#173]
Slack no longer allows overriding the channel the webhook url is linked to https://api.slack.com/messaging/webhooks
> You cannot override the default channel (chosen by the user who installed your app), username, or icon when you're using Incoming Webhooks to post messages. Instead, these values will always inherit from the associated Slack app configuration.

Could support be added for having multiple webhooks URLs available through environment variables so that we can still post to different channels based on the pipeline that is running (e.g. our intended use case is having notifications of failed develop branch builds go to one channel, and another channel that will be notified of deployments to various environments)?

**Comment by KyleTryon** [comment]
Hello @alecwcp,

We are currently working on the next major version of the orb which will not use webhooks, but OAuth tokens: https://github.com/CircleCI-Public/slack-orb/pull/172

This will be slack orb 4.0.0 coming in 2 weeks. We'd love beta testers! 
https://discuss.circleci.com/t/slack-orb-v4-beta/37082

We just merged this change from Webhooks to oauth tokens into the beta earlier today. 

--

Out of curiosity, did this functionality just now stop working for you?

**Comment by alecwcp** [comment]
Hi @KyleTryon 

That looks great! I really should have searched older issues better before posting...
To use the beta version of the orb, do we just add the below to our config
```
orbs:
  slack: circleci/slack@dev:beta
```
I've just been taking a look through https://github.com/CircleCI-Public/slack-orb/issues/77 (followed from https://github.com/CircleCI-Public/slack-orb/pull/172) - I'm still a little hazy on how to setup the beta version of the orb (presumably there are some environment variables that need to be set in CircleCI for the OAuth access to Slack?).

If you don't mind explaining that setup then I'm sure we can be a beta tester.

--

> Out of curiosity, did this functionality just now stop working for you?
We were just discussing getting notifications into Slack today, and one of my teammates shared a link to the orb. We haven't actually started using it yet.

**Comment by gmemstr** [comment]
@alecwcp We are actively working on the documentation for this orb, but here's a quick rundown of steps to get the token.

1. Visit https://api.slack.com/apps and create a new app.
2. Head to the "OAuth & Permissions tab".
3. Under "Scopes", ensure the bot at least has the `chat:write` scope so it can post messages (for specifying custom channels, you will likely want `chat:write.public` so it can post in any public channel).
4. "Install App to Workspace" and follow the prompts.
4. Store the "Bot User OAuth Access Token" as the `$SLACK_ACCESS_TOKEN` environment variable within CircleCI.

At this point, the orb should be able to post messages to Slack successfully!

**Comment by alecwcp** [comment]
Hi @gmemstr  thanks for that, I've followed through that and all appears good.
I was trying to filer the branches to send notifications on using the example here https://github.com/CircleCI-Public/slack-orb/blob/Major-block-kit-redesign/src/examples/only_notify_on_branch.yml
but I get a build error, the end of which is
```
Error calling command: 'slack/notify'
Unexpected argument(s): branch_list
```
Is the branch_list argument not available in the beta version of the orb yet? The orb section of our config looks like this
```
orbs:
  docker: circleci/docker@1.0.1
  slack: circleci/slack@dev:beta
```

**Comment by timothyclarke** [comment]
@alecwcp The 4.0 version of the orb is out
