### ISSUE TITLE
Example 'only_notify_on_branch' has incorrect param

### ISSUE THREAD

**Issue by dsayling** [CircleCI-Public/slack-orb#183]
## Orb version:

4.0.0

## What happened:

param names changed, example out of date
https://circleci.com/developer/orbs/orb/circleci/slack#usage-only_notify_on_branch

## Expected behavior:

example should match params - I'm not sure if anything else is wrong in the example

## Additional Information:

From #181

**Comment by sudiptog81** [comment]
Can I have a try at this?

**Comment by KyleTryon** [comment]
> Can I have a try at this?

Please feel free! We would highly appreciate it.
