### ISSUE TITLE
Should throw error on missing SLACK_ACCESS_TOKEN

### ISSUE THREAD

**Issue by BeyondEvil** [CircleCI-Public/slack-orb#185]
## Orb version:

4.0.0

## What happened:

Notify job passes but no notification is sent.

## Expected behavior:

Notification sent successfully.

## Additional Information:

I had forgotten to set the SLACK_ACCESS_TOKEN environment variable. Was quite surprised when I realized that the issue was the missing env var and no error had been produced.

**Comment by KyleTryon** [comment]
Thank you for sharing this. We will include this in the next patch asap.

**Comment by addb** [comment]
@KyleTryon I have a SLACK_WEBHOOK and SLACK_DEFAULT_CHANNEL configured, but I don't see any slack notification and the error response is
```
{
  "ok": false,
  "error": "not_authed"
}
```
 and build passes as mentioned in the issue. In the steps that i followed Its just adding Webhook and adding slack orbs in the config file. What am I missing here?

**Comment by KyleTryon** [comment]
> @KyleTryon I have a SLACK_WEBHOOK and SLACK_DEFAULT_CHANNEL configured, but I don't see any slack notification and the error response is
> 
> ```
> {
>   "ok": false,
>   "error": "not_authed"
> }
> ```
> 
> and build passes as mentioned in the issue. In the steps that i followed Its just adding Webhook and adding slack orbs in the config file. What am I missing here?

Hello, sorry for the confusion, we are updating the in-app instructions. The setup for Slack orb v4 does not use webhooks, it instead uses OAuth.

More information can be found here. https://github.com/CircleCI-Public/slack-orb/wiki/Setup

**Comment by addb** [comment]
> > @KyleTryon I have a SLACK_WEBHOOK and SLACK_DEFAULT_CHANNEL configured, but I don't see any slack notification and the error response is
> > ```
> > {
> >   "ok": false,
> >   "error": "not_authed"
> > }
> > ```
> > 
> > 
> > and build passes as mentioned in the issue. In the steps that i followed Its just adding Webhook and adding slack orbs in the config file. What am I missing here?
> 
> Hello, sorry for the confusion, we are updating the in-app instructions. The setup for Slack orb v4 does not use webhooks, it instead uses OAuth.
> 
> More information can be found here. https://github.com/CircleCI-Public/slack-orb/wiki/Setup
Thanks @KyleTryon. 
Just to add, at the end of those steps, I had to manually add the app (/invite app_name) into the Slack channel. I think it is better to mention this in the setup doc.
