### ISSUE TITLE
App is not configured for interactive responses slack warning

### ISSUE THREAD

**Issue by BeyondEvil** [CircleCI-Public/slack-orb#188]
## Orb version:

4.0.0

## What happened:

Using the [on-hold template](https://github.com/CircleCI-Public/slack-orb/blob/v4.0.0/src/message_templates/basic_on_hold_1.json) produces a slack warning on the `View Workflow` button.

<img width="524" alt="Screenshot 2020-10-13 at 19 10 58" src="https://user-images.githubusercontent.com/15611634/95894348-3ec96a00-0d89-11eb-9657-13e5aba621ed.png">

## Expected behavior:

No warning.

## Additional Information:

The information in the warning is sort of irrelevant for the use case of the button (simply to open a link). Possible fixes includes either changing what element is being used or add instructions on how to handle this to the Wiki.

**Comment by KyleTryon** [comment]
@BeyondEvil Hello, 

This is expected as the "app" is not a true app, however, you should still be able to click the button and have it work as a link. I can/will investigate deeper but I believe this is a consequence of using interactive elements in the orb. A regular link in markdown would now show such an error but, we like buttons.

**Comment by BeyondEvil** [comment]
Yes, all works "as expected" apart from the (annoying) warning.

Any idea how to silence it? Could I set the callback URL to something like `http://localhost` ?

**Comment by KyleTryon** [comment]
> Yes, all works "as expected" apart from the (annoying) warning.
> 
> Any idea how to silence it? Could I set the callback URL to something like `http://localhost` ?

I have yet to test this but that sounds like it would likely work (I wonder if an error will come up if no response), if so, perhaps we could do this intelligently/automatically as well.

**Comment by BeyondEvil** [comment]
I tried both `http://localhost` and `https://localhost` (for science of course!) and they both give (different) warnings.

However, using `https://postman-echo.com/post` worked since it just swallows whatever you give it and then sends (echo) it back.

Not sure how good/popular it is to use it for our purpose. 😆

**Comment by KyleTryon** [comment]
Glorious service to the both of those. I do not think they would however appreciate how much we could potentially hammer them. We at least understand the issue... Might need to consider something a little creative/local to solve this one. Going to think on this one a bit while we investigate some of the other open issues.

**Comment by Gothicania** [comment]
https://github.com/CircleCI-Public/slack-orb/issues/188#issuecomment-708988009

**Comment by Gothicania** [comment]
https://github.com/CircleCI-Public/slack-orb/issues/188#issuecomment-708988009

**Comment by montanaflynn** [comment]
Is this why the mentions are not clickable and don't trigger a notification as well? 

Having mentions that don't show up in slack notifications isn't very useful.

<img width="144" alt="Screen Shot 2021-01-13 at 13 06 36" src="https://user-images.githubusercontent.com/24260/104413077-2fcca080-55a0-11eb-8241-3f0d5485246b.png">

**Comment by KyleTryon** [comment]
> Is this why the mentions are not clickable and don't trigger a notification as well?
> 
> Having mentions that don't show up in slack notifications isn't very useful.
> 
> <img alt="Screen Shot 2021-01-13 at 13 06 36" width="144" src="https://user-images.githubusercontent.com/24260/104413077-2fcca080-55a0-11eb-8241-3f0d5485246b.png">

This should be unrelated
