### ISSUE TITLE
Does this Orb require any changes to work with DockerHub auth?

### ISSUE THREAD

**Issue by apaleslimghost** [CircleCI-Public/slack-orb#193]
## Describe Request:

When DockerHub starts rate limiting anonymous requests on Nov 1st, it looks like this Orb will be impacted, since there's no `auth` key in [the `docker` config](https://github.com/CircleCI-Public/slack-orb/blob/939b6fe6923792cc405d7a7386acd59f94a7bdc9/src/jobs/on-hold.yml#L36-L37). It looks like a standard pattern is to expect `DOCKERHUB_USERNAME`/`DOCKERHUB_PASSWORD` environment variables (see example), will this (or something equivalent) be required for this Orb?

## Examples:

- https://discuss.circleci.com/t/updated-authenticate-with-docker-to-avoid-impact-of-nov-1st-rate-limits/37567/35

**Comment by KyleTryon** [comment]
Hello @apaleslimghost,

Thank you for checking this out! There will be more communications coming out shortly to discuss this further, but I can confirm this orb _will not_ be affected by the changes at docker. 

That said, it is still best practice to attempt to login if the user provides authentication. I am currently in communications with folks about that pattern, that is likely the pattern we will use.

I have not yet tested but I also want to ensure that if they are blank, there is no negative repercussions. I can confirm though that this will not be a time-sensitive issue for us in this particular use-case.

**Comment by MichaelScheetz-HPE** [comment]
https://github.com/CircleCI-Public/slack-orb/blob/master/src/jobs/on-hold.yml#L37 -- uses an image from dockerhub. Without authenticating to dockerhub this will certainly be impacted by rate limits.

**Comment by KyleTryon** [comment]
> https://github.com/CircleCI-Public/slack-orb/blob/master/src/jobs/on-hold.yml#L37 -- uses an image from dockerhub. Without authenticating to dockerhub this will certainly be impacted by rate limits.

More information will be coming but I can 100% guarantee this will _not_ be affected.

**Comment by KyleTryon** [comment]
Some more information has been released. I believe we will be doing a longer and more detailed announcement soon as well.
https://discuss.circleci.com/t/updated-authenticate-with-docker-to-avoid-impact-of-nov-1st-rate-limits/37567/52

The main point from this post is, the namespace under which CircleCI published our own Docker images `cimg` and `circleci` will not be affected by rate limits for the foreseeable future. 

We do however still encourage users to add their own Docker credentials, especially in instances of private or non-circleci images.
