### ISSUE TITLE
Update Docs: `@` mention Slack App in channel required permissions

### ISSUE THREAD

**Issue by JohnMahowald** [CircleCI-Public/slack-orb#194]
## Describe Request:
Requesting an update to the setup wiki documentation, and potentially an update to the notify.sh script.

I recently was integrating CircleCi with the slack orb. The [setup documentation](https://github.com/CircleCI-Public/slack-orb/wiki/Setup) is missing a critical step where an installing user must *add their newly created application to the channels it will notify*.

This was particularly hard to debug, because of the `> /dev/null` at the end of this line of the `notify.sh` script.

https://github.com/CircleCI-Public/slack-orb/blob/master/src/scripts/notify.sh#L41

It may make sense to remove the `> /dev/null` the response of the `notify` curl request to help developers in the future reading the CI console output. I'll put together a PR in the event that is useful.

Thanks!

## Examples:

Here is an example of a potential addition to the documentation:
https://github.com/JohnMahowald/slack-orb/wiki/Setup

## Supporting Documentation Links:
https://github.com/CircleCI-Public/slack-orb/blob/master/src/scripts/notify.sh#L41
https://github.com/JohnMahowald/slack-orb/wiki/Setup

EDIT: created a pr - https://github.com/CircleCI-Public/slack-orb/pull/195

**Comment by JohnMahowald** [comment]
@KyleTryon 👆🙏👊

**Comment by gmemstr** [comment]
I feel the more correct way around this is to add the `chat:write.public` permission to the bot, rather than requiring an invite to each channel.

**Comment by KyleTryon** [comment]
@JohnMahowald I would love to know if this did not work for you as intended. When creating your application, was the `chat:write` scope given to the OAuth token? 
https://github.com/CircleCI-Public/slack-orb/wiki/Setup#2-permissions

https://api.slack.com/scopes/chat:write

As a bot, I believe this should give it access to post in any non-private channel.

**Comment by JohnMahowald** [comment]
@KyleTryon 

I created the application with the prescribed scopes. Here is a screenshot from the app I created:
<img width="708" alt="Slack_API__Applications___Wednesday_Slack" src="https://user-images.githubusercontent.com/4701587/96299409-e1abff00-0fa8-11eb-9e42-73198b61f2c0.png">

After some debugging, I found the response I was getting from the `chat.postMessage` api was
```
{
    "ok": false,
    "error": "not_in_channel"
}
```
I `@` mentioned my new App in the group, sent an invitation, and then was able to get a success response.

Alternately, as per @gmemstr 's recommendation, I just verified adding the `chat:write.public` scope will allow me to achieve the same behavior without `@` mentioning the App in the channel:

<img width="720" alt="Slack_API__Applications___Wednesday_Slack" src="https://user-images.githubusercontent.com/4701587/96300200-02c11f80-0faa-11eb-9f1a-a3c81df74a0e.png">

**Comment by KyleTryon** [comment]
Thank you @JohnMahowald. I think we may then want to update our docs with the public version of chate:write

**Comment by KyleTryon** [comment]
The docs have been updated and we are in the process of updating in-app instructions as well. Thank you!
