### ISSUE TITLE
Unclear event values

### ISSUE THREAD

**Issue by blacelle** [CircleCI-Public/slack-orb#200]
In examples provided in https://circleci.com/developer/orbs/orb/circleci/slack#usage-successful_tagged_deployment,

event key is associated to 'success, while the Orb description indicates values can be one of 'pass', 'fail' and 'always'.

Which one is correct between 'pass' and 'success?'

**Comment by KyleTryon** [comment]
Thank you for pointing this out @blacelle. This was a mistake left over during the development. The real value is indeed "pass", as indicated by the documentation. We will update the example as part of the next patch.
