### ISSUE TITLE
CCI_STATUS empty in Slack Sending Notification job step

### ISSUE THREAD

**Issue by bmilekic** [CircleCI-Public/slack-orb#204]
## Orb version:

2.1

## What happened:

I am using orb circleci/slack@4.1.1 which is the latest documented on circleci docs at the time of this writing.

I have a slack/notify step at the end of my macos/xcode tests job, which has `event` set to `pass`. While the job passes and I see the "Slack - Detecting Job Status (PASS)" step runs with the following code:

```
#!/bin/bash --login -eo pipefail
echo 'export CCI_STATUS="pass"' > /tmp/SLACK_JOB_STATUS
```

The subsequent "Slack - Sending Notification" step decides to skip sending the notification, and it seems that `CCI_STATUS` environment variable is empty from within it. Here are the last 4-5 lines of the Sending Notification job output:

```
NO SLACK ALERT

This command is set to send an alert on: pass
Current status: 
CircleCI received exit code 0
```

Notice `Current status:` showing up as empty, indicating CCI_STATUS is empty, which explains why the step decided `NO SLACK ALERT`.

Note that if I set `event: always` in my config.yml for the slack/notify step, the notification is sent to Slack as expected, but that's not what I want: I want it to only be sent on job pass.

## Expected behavior:

Explained above. I'd expect the final notification step to decide to send the notification as my job has passed.

## Additional Information:

- orb circleci/slack@4.1.1
- macos/xcode 12.1.0

**Comment by KyleTryon** [comment]
Hello @bmilekic,

Sorry about this, this may be in response to a change that was made yesterday and then should have been quickly patched in 4.1.1 (4.1.0 should have had the bug). I just ran a quick test and I do not believe I am able to replicate the issue.

Would it be possible to ask for a link to your job on CircleCI where you encountered this bug? If you rather not share the link in public we can communicate via CircleCI support or Twitter.

**Comment by bmilekic** [comment]
Hi @KyleTryon 

Thanks for your quick reply. I just filed request #81067 via CircleCI Support, and included the information you requested there.

Best,
Bosko

**Comment by bmilekic** [comment]
My sincere apologies. I made a mistake when filing this this morning and just found out that I was in fact running with orb 4.1.0 which I think has this problem.

I just switched to 4.1.1 where things are working again. Closing this bug, and will also close the support request.

**Comment by KyleTryon** [comment]
@bmilekic Not a problem at all! Thank you for confirming, that's helpful to us :D.

Sorry for the inconvenience!

**Comment by baptLesta** [comment]
@bmilekic Juste wanted to thank you, I made the same mistake and this post solved my issue 🤗

**Comment by princed** [comment]
Hi @KyleTryon, I have a similar problem.

I am running `circleci/slack@4.1.2` and the line `. "/tmp/SLACK_JOB_STATUS"` is present in the script, however `CCI_STATUS` is still empty as you can see on the screenshot:

<img width="910" alt="image" src="https://user-images.githubusercontent.com/796050/100031364-96a7c600-2e49-11eb-8e9c-2c3b740f87ec.png">

**Comment by ghasemel** [comment]
Hi, I have the same problem on 4.1.2, by switching back to 4.1.1 works again

**Comment by nickpalmer** [comment]
The `./tmp/SLACK_JOB_STATUS` needs to come BEFORE ShouldPost.

**Comment by KyleTryon** [comment]
Hey all, apologies for this. We'll look into more extensive e2e tests to verify that our tests not only pass, but perhaps we begin to validate the actual test output posted to our debugging slack channel.

A patch update has been released: `4.1.2`

**Comment by schankam** [comment]
Getting the same issue with 4.1.2 as of today.

Reverting to 4.1.1 works

**Comment by brianlow** [comment]
Same problem and fix here as well. The [examples at CircleCI](https://circleci.com/developer/orbs/orb/circleci/slack) use v4.0

**Comment by danielpsf** [comment]
Same issue with the version that is shown in the documentation here https://circleci.com/developer/orbs/orb/circleci/slack.

`4.1.3`

😢

**Comment by KyleTryon** [comment]
Can anyone confirm if the latest version `4.1.4` is causing them any issues related to incorrect or missing statuses?

**Comment by Gegil23** [comment]
@KyleTryon I had the same issue and it is working as expected with `4.1.4`.

**Comment by KyleTryon** [comment]
> @KyleTryon I had the same issue and it is working as expected with `4.1.4`.

Thank you for your confirmation 🙏. I appreciate your help. Going to mark this as closed.
