### ISSUE TITLE
Impossible to filter on empty tag name.

### ISSUE THREAD

**Issue by rogersd** [CircleCI-Public/slack-orb#210]
## Orb version:
4.1.1

## What happened:
I tried to add a `tag_pattern` parameter that would only match tags that followed the semver pattern, in order to filter out automatic deployments that have no tag.  Unfortunately, this code:

```
FilterBy() {
    if [ -z "$1" ] || [ -z "$2" ]; then
      return
    fi
```

Will always return on an empty tag name (`$2`), even if it doesn't match the supplied regex.

## Expected behavior:

Providing a valid `tag_pattern` regex should skip empty tag names.

**Comment by rogersd** [comment]
@skyeagle @KyleTryon Can one of you please take a look at this?  The repeated notifications on untagged deployments are annoying my integration team.

Thanks.

**Comment by skyeagle** [comment]
@rogersd it matches either tag name or branch name. You can try something like that if I understand properly your use case:

```yaml
branch_pattern: something_that_will_never_match
tag_pattern: your_tag_match
```

Let me know if that works for you and sorry for any inconvenience that it may have caused.

**Comment by rogersd** [comment]
Just to explain my use case a bit more, let's say I have my `master` branch and four environments.  The deployment can be triggered in one of four ways:

Automatically deployed to the `dev` environment on merge to `master`.  (No tag.)
Deployed to `QA` with a `#.#.#-qa#` tag.
Deployed to `staging` with a `#.#.#-rc#` tag.
Deployed to `production` with a `#.#.#` tag.

So, in the first case, there won't be a tag, but in all cases the branch name will be the same (`master`).  

What I'd like is to not have the first case send a notification.  The problem is that I can't filter on the tag in the first case because the tag is empty.  I had tried passing a regex of `[0-9]+\.[0-9]+\.[0-9].*` as the `tag_pattern`, but the notification went through anyway.

**Comment by skyeagle** [comment]
hey @rogersd how about trying something like that:

```yaml
branch_pattern: ""
tag_pattern: [0-9]+\.[0-9]+\.[0-9]+(-.+)?
```

it's supposed to send notification on matched tags only and disregard branched

```
❯ echo "12.12.12-qa1" | grep -Eq "^[0-9]+\.[0-9]+\.[0-9]+(-.+)?$" && echo "send notification"
send notification
❯ echo "12.12.12-rc2" | grep -Eq "^[0-9]+\.[0-9]+\.[0-9]+(-.+)?$" && echo "send notification"
send notification
❯ echo "12.12.12" | grep -Eq "^[0-9]+\.[0-9]+\.[0-9]+(-.+)?$" && echo "send notification"
send notification
❯ echo "12.12" | grep -Eq "^[0-9]+\.[0-9]+\.[0-9]+(-.+)?$" && echo 'send notification'
# no send
```

let me know if that works

**Comment by rogersd** [comment]
Thanks for the suggestions.  I ended up moving the notification for success to a separate job that I could call only when needed.
