### ISSUE TITLE
Notify command doesn't install JQ on Alpine

### ISSUE THREAD

**Issue by ralbertazzi** [CircleCI-Public/slack-orb#211]
The `InstallJq` function doesn't actually install JQ on Alpine:

https://github.com/CircleCI-Public/slack-orb/blob/5435b8129cdade77c990e6e07ae7de0f0a4c0261/src/scripts/notify.sh#L89

**Comment by KyleTryon** [comment]
@ralbertazzi This is expected as it is hard to guarantee we will be able to install JQ on an alpine image as it is a common convention to both not be the root user, or have sudo installed on Alpine images.

There also does not appear to be an alpine release included in the official JQ Github releases.

**Comment by tfennelly** [comment]
@KyleTryon So what's the recommended workaround for this?

We have a job that uses an image based on Alpine. That image doesn't have JQ, resulting in the following error:

```
Checking For JQ + CURL: Alpine
SLACK ORB ERROR: JQ is required. Please install
```

Also ... this fails the job, which doesn't seem ideal.

**Comment by KyleTryon** [comment]
> @KyleTryon So what's the recommended workaround for this?
> 
> We have a job that uses an image based on Alpine. That image doesn't have JQ, resulting in the following error:
> 
> ```
> Checking For JQ + CURL: Alpine
> SLACK ORB ERROR: JQ is required. Please install
> ```
> 
> Also ... this fails the job, which doesn't seem ideal.

Hello. 

JQ must be installed on the image before utilizing the Slack orb. JQ could be installed manually via your config, or it must be included in your docker image. At this time JQ is a hard dependency of the Slack orb and we do not at this time anticipate removing it.

At some point in the future we will offer a full slack bot which will not utilize orbs at all (but would also inherently have less customization)

**Comment by tfennelly** [comment]
@KyleTryon Thanks for the fast reply.

**Comment by rattrayalex** [comment]
You can do this with an orb:

```
orbs:
  slack: circleci/slack@4.4.2
  jq: circleci/jq@2.2.0

jobs:
  test-slack:
    steps:
      - jq/install
      - slack/notify: #...
```
