### ISSUE TITLE
Notify command should stop as soon as possible when no notification should be sent

### ISSUE THREAD

**Issue by ralbertazzi** [CircleCI-Public/slack-orb#212]
The line referenced below should be executed as soon as possible so we avoid taking unnecessary steps (such as installing dependencies) if no notification should be sent (e.g. the notification should be sent on fail but the job passed). This will make the CI faster when no Slack message needs to be sent.

https://github.com/CircleCI-Public/slack-orb/blob/5435b8129cdade77c990e6e07ae7de0f0a4c0261/src/scripts/notify.sh#L43

**Comment by gmemstr** [comment]
Fixed in #213

**Comment by ralbertazzi** [comment]
Thank you!! 🙏
