### ISSUE TITLE
Config keys that allows specifying CircleCI -> SlackID mappings + the ability to automatically mention the commiter

### ISSUE THREAD

**Issue by 0xdevalias** [CircleCI-Public/slack-orb#214]
## Describe Request:

Currently we appear to have access to Slack mentions via `SLACK_PARAM_MENTIONS`, but to my knowledge this requires the CircleCI username and the Slack username to be aligned. It would be great if we had some easy way of mapping the CircleCI usernames to Slack usernames, so that we can easily and automatically mention the committer causing a failure, etc; rather than the whole channel/team each time.

## Examples:

eg. in https://github.com/abeyuya/actions-mention-to-slack#example-usage we can configure mappings like:

`.github/mention-to-slack.yml`
```
# For Github User
# github_username: "slack_member_id"

github_username_A: "slack_member_id_A"
github_username_B: "slack_member_id_B"
github_username_C: "slack_member_id_C"
abeyuya: "XXXXXXXXX"

# For Github Team
# github_teamname: "slack_member_id"

github_teamname_A: "slack_member_id_D"
```

## Supporting Documentation Links:

- https://circleci.com/developer/orbs/orb/circleci/slack

**Comment by klsetzer** [comment]
For teams that have numerous projects, this would have to be duplicated and maintained in each project, would it not?

How about using JSON extracted from an environment variable in addition to, or instead of a YAML file in the repo? That way, CCI contexts could be used to populate this globally.

**Comment by KyleTryon** [comment]
So, we in CircleCI used to do something internally that we could maybe add to the wiki. I'll start by saying there is no perfect solution here without CircleCI implementing a Slack authentication service, and in the future hopefully a full-fledged bot. 

```
but to my knowledge this requires the CircleCI username and the Slack username to be aligned.
```

Slack in this case is _only_ concerned with the Slack username, it does not need to match anything in CircleCI. But if you wanted to, for instance, Slack ping the author of a commit (based on their GitHub name), that would be difficult in the current system.

As @klsetzer mentioned, this config mentioned here would need to be shared among each project.

However, this is similar to what we here at CircleCI have done before. You could save the JSON object in a context on CircleCI, a set of environment variables that can be shared org wide.
https://circleci.com/docs/2.0/contexts/

This is not likely something we will take on officially for the Orb, but instead will continue to investigate a native authentication.

**Comment by xander-marjoram** [comment]
If it makes any difference, I would also like this feature to be implemented.

We have quite a large team of engineers working on a component library, and currently our options are for either everyone to be alerted when a build fails, or nobody. Neither of these are ideal.

@KyleTryon please could you give an example of how you have wired it up so that you can access the slack user ids from the context?

**Comment by 0xdevalias** [comment]
> @KyleTryon So, we in CircleCI used to do something internally that we could maybe add to the wiki.

That would be useful. Can you link it here if you do end up adding it?

> I'll start by saying there is no perfect solution here without CircleCI implementing a Slack authentication service, and in the future hopefully a full-fledged bot.

That would be an even better solution from my perspective!

> As @klsetzer mentioned, this config mentioned here would need to be shared among each project.
> 
> However, this is similar to what we here at CircleCI have done before. You could save the JSON object in a context on CircleCI, a set of environment variables that can be shared org wide.
> https://circleci.com/docs/2.0/contexts/

I would be happy to add it to a `context`, though how would we then go about using it from there? (see above RE: how you do it internally/wiki)

> This is not likely something we will take on officially for the Orb, but instead will continue to investigate a native authentication.

Native authentication sounds like a great solution to me. Excited to see it happen.

**Comment by KyleTryon** [comment]
@danielpsf to address your request specifically we have added a new patch update. However we will leave this issue open for now as I do not believe the original request for this issue has yet been addressed (and we will do our best to asap).

**Comment by Gothicania** [comment]
notify:
          channel: api-and-services-internal
          event: fail
          mentions: '@here'
          template: basic_fail_1

**Comment by EricRibeiro** [comment]
There is no secure way to achieve this easily, but we hope to solve this with future alternative integrations.
