### ISSUE TITLE
Setup Wiki screenshots are out of date

### ISSUE THREAD

**Issue by vkurup** [CircleCI-Public/slack-orb#230]
## Describe Request:

Please update https://github.com/CircleCI-Public/slack-orb/wiki/Setup to match the screenshots in the current Slack app creation process

## Examples:

I did not take screenshots, but the ones in the Wiki in steps 2 and 3 are significantly different than what is on the Slack website. (That's as far as I've gotten in the process)

**Comment by KyleTryon** [comment]
Hello @vkurup,

I have taken a look and as far as I can tell, the screenshots appear to match what I see on Slack's website. Could you share what you are seeing for comparison?

**Comment by vkurup** [comment]
Hi @KyleTryon,

Interesting... maybe I am on a different type of Slack plan or something? I see the exact same step 1 screenshot but then I see this for step 2:
![image](https://user-images.githubusercontent.com/4413/107269317-708ccd80-6a17-11eb-9e53-e66e05f98850.png)

The instructions say to look for `scopes`, but I don't see that. I do see Permissions, so if I click that, I can find a section called Scopes where I can continue following the instructions successfully.

I then click the "Install to Workspace" green button and this time I DO see the "Oauth Tokens & Redirect URLs" so I can grab the Oauth token. (I swear that I couldn't find this last time and was instead taken to the following screen, and none of the tokens on this screen match the Oauth token format properly):
![image](https://user-images.githubusercontent.com/4413/107270048-70d99880-6a18-11eb-8211-1fecfe0d77ee.png)

So I got stuck at that point and couldn't figure out how to get the Oauth token. 

It is very possible that this was my error, so feel free to close this ticket (though it would be nice to figure out how to get an Oauth token if you miss that screen like I did, short of deleting the app and starting over)

**Comment by KyleTryon** [comment]
Thanks for the additional info @vkurup 👍 indeed it looks like there is a middle step there of clicking "permissions" first. I believe when first creating an app if had guided you through this process and when checking now manually I was looking at an existing app, so things may have changed in the original setup.

Ill update the docs to reflect this in case folks miss it. Thank you!
