### ISSUE TITLE
branch_pattern regex matching doesn't work for negative matching

### ISSUE THREAD

**Issue by montanaflynn** [CircleCI-Public/slack-orb#231]
## What happened:

I added `^(?!(master|staging)$).+$` to my branch filter and it stopped matching anything.

## Expected behavior:

It would match all branches except master and staging.

Here's a link to the regex and what it normally matches: https://regex101.com/r/emL1ei/1

## Additional Information:

After testing the [BranchFilter](https://github.com/CircleCI-Public/slack-orb/blob/654c36b90da72daf0cf067c4f600d54005644207/src/scripts/notify.sh#L97) shell function I found the problem is using grep with the `-E` "extended regex" flag to handle the matching. This doesn't support the regex I need to match all branches except for some. I think the docs just say "regex" but don't mention the flavor or specific limitations of grep's regex.

I did get it to work by changing the grep `-E` flag to `-P` which makes it use perl regex which is more full featured and probably commonly understood or used in programming. I would suggest changing it to use `-P` or adding documentation about the branch pattern regex shortcomings.

Alternatively maybe you could add the inverse of `branch_pattern` somehow so I could list the branches I don't want to run. This could be done using `grep -v`.

**Comment by daivinhtran** [comment]
I have the same problem as yours. The workaround is to use [conditional steps](https://circleci.com/docs/2.0/reusing-config/#defining-conditional-steps) at a higher level.

**Comment by EricRibeiro** [comment]
Closing the issue as this was fixed in #196.
