### ISSUE TITLE
Template with links to test results

### ISSUE THREAD

**Issue by hvitis** [CircleCI-Public/slack-orb#232]
## Describe Request:

When slack notification arrives I would like to have a button that would lead me to my artefacts / test results. A template that would automatically returning link to results in some way.

## Examples:

Currently I am doing it like that:

1. Installing [jq][0]
2. Running bash script

```
export URL_API_TEST_RESULTS=$(curl -s --location --request GET "https://circleci.com/api/v1.1/project/github/hvitis/youtalky.com/$CIRCLE_PREVIOUS_BUILD_NUM/artifacts" --header "Circle-Token: $CIRCLE_API_TOKEN" | jq -r '.[0].url')
if [ -z "$URL_API_TEST_RESULTS" ]
then
      echo "Unable to get URL_API_TEST_RESULTS variable, exiting with code 1";
      exit 1;
else
      echo $(eval "echo API Tests are located at: $URL_API_TEST_RESULTS");
fi
```
Passing variable to Button block

```
{
    "type": "button",
    "text": {
                  "type": "plain_text",
                  "text": "View API Test Results"
                },
    "url": "${URL_API_TEST_RESULTS}"
}
```

Where __URL_API_TEST_RESULTS__  is:
```
https://XXX-2958XXXX7-gh.circle-artifacts.com/0/test-results/results.html
``` 

[0]: https://stedolan.github.io/jq/

**Comment by EricRibeiro** [comment]
Thank you for the suggestion! We want to add a feature for this. However, the dependency on the CircleCI API and the personal access token adds a new hard dependency that we would like to avoid making standard at the moment; however, we encourage you to continue developing custom templates.

We will look into adding this in the future if the token no longer becomes necessary.
