### ISSUE TITLE
Yarn Debian key expiry date updated (EXPKEYSIG 23E7166788B63E1E)

### ISSUE THREAD

**Issue by siddheshbhasme** [CircleCI-Public/slack-orb#235]
## Orb version: 
4.1.1

## What happened:
When using the slack orb as part of a CircleCI jobs, we encoutered following error when Orb tries to install `jq`:

```
W: GPG error: https://dl.yarnpkg.com/debian stable InRelease: The following signatures were invalid: EXPKEYSIG 23E7166788B63E1E Yarn Packaging <yarn@dan.cx>
E: The repository 'https://dl.yarnpkg.com/debian stable InRelease' is not signed.
```

## Expected behavior: 
Should install `jq` and should run without errors

## Additional Information: 
Relates to https://github.com/yarnpkg/yarn/issues/7866

Possible Fix - https://github.com/yarnpkg/yarn/issues/7866#issuecomment-772940948

**Comment by siddheshbhasme** [comment]
We re-built the docker image we are using and this is resolved now.

**Comment by pixartist** [comment]
still happening
