### ISSUE TITLE
Add CHANGELOG

### ISSUE THREAD

**Issue by ralbertazzi** [CircleCI-Public/slack-orb#236]
The repo lacks a proper CHANGELOG so it's not possible to quickly read about new features / bug fixes or about the migration steps from one major to another.

Use case: I want to migrate from version 3.4.2 to latest (4.2.1). Where can I find the information to help me in the migration process?

**Comment by KyleTryon** [comment]
Hello @ralbertazzi,

That is on us for not properly maintaining a changelog, though we do attempt to do this through the commit messages if you view the history.

though to answer your question, you are not able to migrate from a version previous to 4.0.0 to 4+, the slack orb has been re-written and improved. It no longer uses webhooks and instead uses OAuth with the Slack API.

I would recommend starting at our Wiki from the start: https://github.com/CircleCI-Public/slack-orb/wiki

There is also this blog post from the initial release: https://circleci.com/blog/circleci-slack-integration/
