### ISSUE TITLE
Allow custom templates defined in separate files

### ISSUE THREAD

**Issue by bunker-inspector** [CircleCI-Public/slack-orb#237]
## Describe Request:
I feel like this orb creates a lot of noise in your config if you're not using one of the pre-defined templates. Would be great if we could use a custom template defined in a separate JSON file in the .circleci directory somewhere in our project

## Examples:
```
- slack/notify:
      event: fail
      template: my_custom_template
```

## Supporting Documentation Links:

**Comment by KyleTryon** [comment]
Hello @bunker-inspector,
Templates can come from a variety of places, including files or environment variables. 
https://github.com/CircleCI-Public/slack-orb/wiki/Dynamic-Templates

I recommend creating a context containing all of your custom templates.
 https://circleci.com/docs/2.0/contexts

This way you can share them across projects.

**Comment by bunker-inspector** [comment]
Ah that works like a charm! Thank you and sorry for the distraction @KyleTryon
