### ISSUE TITLE
Slack is not authorized with token

### ISSUE THREAD

**Issue by ondrejdolezal93** [CircleCI-Public/slack-orb#238]
## What happened: 

Hello, I followed the installation steps:

1. Created a CircleCI Slack app 
2. Set the correct permissions
3. Installed and wrote down oauth token
4. Added _SLACK_ACCESS_TOKEN_ and _SLACK_DEFAULT_CHANNEL_ to organization's default channel.
5. Added slack orb to my CircleCI config and added _slack/notify_ step:

```
- slack/notify:
          custom: |
            {
              "blocks": [
                {
                  "type": "section",
                  "fields": [
                    {
                      "type": "plain_text",
                      "text": "*This is a text notification*",
                      "emoji": true
                    }
                  ]
                }
              ]
            }
          event: always
```

6. Double checked the variables from step 4
7. Ran the worfkflow: Everything works fine, but:

- slack notification is not sent, as I receive following error: 

```
Sending to Slack Channel: *********
Slack API returned an error message:
"not_authed"
```

I SSHed into the container and checked the variables from step 4, they are set correctly.

## Expected behavior:

I expect token to be used and notification to be successfully sent.

Thank you in advance

**Comment by KyleTryon** [comment]
Hello @ondrejdolezal93,

The error you are receiving is directly from the Slack API and _should_ not be directly related to the orb (it's possible but it doesnt seem to be at the moment). You should be able to confirm this by attempting a manual API call.

You post seems to imply you likely have already done this but just to be sure, ensure you are following the steps on this page directly: https://github.com/CircleCI-Public/slack-orb/wiki/Setup

I would recommend clearing out your existing application/variables and starting fresh to be sure.

We'll be sure to leave this open until your issue has been resolved and give other folks an opportunity to chime in if anyone else is currently experiencing issues (in the case that perhaps Slack changed their API or something).

**Comment by ondrejdolezal93** [comment]
I tried using the existing template, it did not help. Could you please point me to way of making a simple Slack API call to test the authorization?

**Comment by ondrejdolezal93** [comment]
I am sorry, this was my fault - my colleague entered variable with white space at the beginning into CircleCI context, everything started working just fine after editing it.

Thanks, Ondrej
