### ISSUE TITLE
Step reports success even if alert fails.

### ISSUE THREAD

**Issue by dhalperi** [CircleCI-Public/slack-orb#25]
<img width="450" alt="screen shot 2019-01-03 at 6 49 40 pm" src="https://user-images.githubusercontent.com/526415/50671713-653d5d00-0f88-11e9-8adc-87ab519516cb.png">

My relevant config:

```
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -1,4 +1,8 @@
 version: 2.1
+
+orbs:
+  slack: circleci/slack@0.1.15
+
 jobs:
   build:
     docker:
@@ -23,6 +27,8 @@ jobs:
+      - slack/status:
+          fail_only: 'true'
```

**Comment by dhalperi** [comment]
(Obviously the docker image I'm using doesn't have `curl`, and that's on me. A separate issue from the exit code being wrong.)

**Comment by KyleTryon** [comment]
I believe the ask here would be to check for the existence of CURL and fail early in the build `exit 1` if curl is missing.

**Comment by piyush-insider** [comment]
@KyleTryon I would like to tackle this.

**Comment by eddiewebb** [comment]
Closing per Kyle's comment in #81
