### ISSUE TITLE
Pre-orb integration + universal message

### ISSUE THREAD

**Issue by ondrejdolezal93** [CircleCI-Public/slack-orb#251]
## Describe Request: Unlink pre-orb Slack integration, set universal Slack message

Hello, we used pre-orb Slack integration. Now, when we open project and click Slack integration, official Slack orb documentation opens, my question is: what is the proper way to turn off pre-orb Slack notification for our projects?

Another question is: how to set universal Slack message for all of our projects?

I got it working for specific projects using  Circle's _config.yml_, but what if I want to edit the message for all of my repositories?
Editting this file manually one by one for all of my repos seems to be a bad solution.

Thanks, Ondrej

**Comment by KyleTryon** [comment]
For CircleCI specific related questions (anything regarding the old Slack integration), please submit a request to CircleCI support: https://support.circleci.com/hc/en-us/requests/new

> Another question is: how to set universal Slack message for all of our projects?

You can save custom message templates within a CircleCI Context and use it within the Slack Orb's notify command: https://github.com/CircleCI-Public/slack-orb/wiki/Reuse-Custom-Templates

The Slack orb itself must be configured for any project that will utilize it, but the message templates can be shared via contexts.

**Comment by KyleTryon** [comment]
If you have further questions about the orb please feel free to include them below. As there is no bug or feature request here I will close the issue for now.
