### ISSUE TITLE
Valid regex in tag_pattern doesn't correctly match tag

### ISSUE THREAD

**Issue by nbialostosky** [CircleCI-Public/slack-orb#257]
## Orb version:

`4.3.1`

## What happened:

When passing a valid regex pattern to `tag_pattern` for the `slack/notify` command, a tag that matches that pattern doesn't trigger a message.

Steps to replicate:
1. Set your `tag_pattern` on your `slack/notify` command to `v\d+\.\d+\.\d+`
2. Set your filter for the job to run to:

```
          filters:
            tags:
              only: /^v\d+\.\d+\.\d+$/
```
3. Commit these changes
4. Add a tag that matches and push it up i.e. `git tag "v1.2.3"` and then `git push --tags`
5. You will find that the message does not send despite the regex matching the tag

## Expected behavior:

Similar to the regex working for the filter key to actually trigger the build, the slack Orb should correctly send the message as the pattern matches.

## Additional Information:

1. I did not include the `^` or the `$` since it seems like the Orb does that automatically, I tried it both ways for what it's worth and neither worked
2. The workaround here is to use a different regex pattern that functionally does the same thing i.e.:

```
tag_pattern: v[0-9]+\.[0-9]+\.[0-9]+
```

**Comment by EricRibeiro** [comment]
Hi, @nbialostosky 👋 

I believe the issue here is that the orb already adds `^` at the beginning and `$` at the end (see [L103](https://github.com/CircleCI-Public/slack-orb/blob/master/src/scripts/notify.sh#L103)).

You should pass as an argument only your tag formatting: `v\d+\.\d+\.\d+`.

Let me know if you have further inquiries.

**Comment by Vanals** [comment]
Hi @nbialostosky  I am probably having a similar proble, not sure if the solution is exactly the same. Still need to try.

But you are speaking about "two different regex patterns". Do the two different patterns have a name? So i can read more about them and I guess find a work around for my issue too.

https://github.com/CircleCI-Public/slack-orb/issues/355
