### ISSUE TITLE
Error `$BASH_ENV: ambiguous redirect` on setting success status 

### ISSUE THREAD

**Issue by gsaslis** [CircleCI-Public/slack-orb#26]
I'm trying to use the slack orb in a centos based image, where I am using https://www.softwarecollections.org/en/  and the `scl enable` command-line tool, which basically does `unset BASH_ENV`. 

as such, https://github.com/CircleCI-Public/slack-orb/blob/master/src/%40orb.yml#L126 and https://github.com/CircleCI-Public/slack-orb/blob/master/src/%40orb.yml#L131 fail in my jobs, with the error: 

```bash
$BASH_ENV: ambiguous redirect
```

I've seen that there is an additional environment variable being added to the builds: `CIRCLE_SHELL_ENV`. I haven't found how it's added still, but I was wondering if it would make sense to use this instead?

It _somehow_ does have the correct value inside my container (i.e. it has picked up the change that `scl enable` did). 

Any hints or other workarounds welcome here!

**Comment by lokst** [comment]
@gsaslis Might setting `BASH_ENV` to `$CIRCLE_SHELL_ENV` work as a workaround?

**Comment by gsaslis** [comment]
@lokst I don't have an env to test this on any more and it looks like the orb structure has changed - I'm not sure when I'll find the time to properly look into this. 

I guess if the steps I mentioned above don't help you reproduce the problem, we can close this issue.

**Comment by lokst** [comment]
@gsaslis I'll close this issue for now (@KyleTryon feel free to weigh in or reopen it if you have other thoughts on this)
