### ISSUE TITLE
Add event type "pass after fail"

### ISSUE THREAD

**Issue by xtreding** [CircleCI-Public/slack-orb#260]
## Describe Request:

In many cases companies would like to have slack notifications know about:
- build failed
- build fixed

For instance: a big project has dozens Pull Requests per day and Maintainers have to make sure everything works. It's important to know when a build is failed (fail event) and it's important to know when the build is fixed too. At present `slack-orb` doesn't have an opportunity to send notifications on `pass after failed`.

Please add this event type. 👍

**Comment by KyleTryon** [comment]
Hello @xtreding,

While this _may_ be possible to detect, we have held off on adding this feature for the following reasons:

- "Fixed" is not a status in CircleCI's API at this time. We can infer if a workflow of the same name from the previous pipeline as succeeded or failed (may be on hold) to compare against the current workflow.
- Not possible to grab the current state. The Slack orb operates within a job within a workflow, it has not yet completed. So it is very difficult to say the current workflow has "passed" if it hasn't yet completed.
- This would at minimum require a CircleCI personal access token. This isn't currently required and reducing the number of long-lived API keys is preferred when possible.

These types of issues could be mitigated potentially in the future with the addition of Webhooks to CircleCI (more info coming). You would not be able to use the orb with webhooks however, this would be an alternative integration.

I hope we can eventually combine these technologies with a true Slackbot, which would receive data both from the orb and webhooks. For now we are somewhat limited in what we can determine about the state of a workflow.

**Comment by freywaid** [comment]
Asking to re-open this bug.  As a possible sol'n, can't you store an artifact reflecting the last build failed on the branch and then use that to determine if we should notify if that the branch was "fixed"?
