### ISSUE TITLE
Slack Orb silently fails to trigger when using CircleCI "base" image

### ISSUE THREAD

**Issue by jon-flowers** [CircleCI-Public/slack-orb#267]
## Orb version:

4.4.0

## What happened:

* I am attempting to add Slack notifications to several  jobs in my workflow
* During testing, I noticed that the Slack notification did not trigger for several jobs, no matter how I attempted to configure it.  I was first trying to add them as `post-steps`, but even when adding directly to the job they never trigger
* Through some trial and error, I figured out that it was only three jobs that are having this problem.  All three of them are using the CircleCI "base" image: `cimg/base:2020.01`
* This image is meant to be very lightweight and works very fast for these jobs, but for some reason it causes the steps related to this orb to be completely skipped over
* See URLs below for more info:
* https://circleci.com/developer/images/image/cimg/base?utm_medium=SEM&utm_source=gnb&utm_campaign=SEM-gnb-DSA-Eng-ni&utm_content=&utm_term=dynamicSearch-&gclid=CjwKCAjwj6SEBhAOEiwAvFRuKCKHRCju4TtH1G6JvJu19ndODkYALZIjx4UW_c5_-97sTUv9ynhg7xoCNOAQAvD_BwE
* https://circleci.com/blog/announcing-our-next-generation-convenience-images-smaller-faster-more-deterministic/
* 

## Expected behavior:

* Either the Slack notification should work as expected, **or** there should be an obvious failure error
* I would assume the orb itself shouldn't just be ignored

## Additional Information:

* I attempted to look for other similar cases of this happening and didn't see anything
* As mentioned above, it is my assumption that the base image is the issue; however I cannot figure out why it just completely ignores the Slack-orb related steps

Config for one of the three jobs (`installJDK`):

```
    installJDK:
        <<: *baseDefaults
        steps:
            - restore_cache: *restore-jdk-cache
            - run:
                  name: Install openjdk from release tar
                  command: |
                      export version=8
                      export update=275
                      export build_no=01

                      if [ ! -d $JAVA_HOME ];then
                          wget https://github.com/AdoptOpenJDK/openjdk8-binaries/releases/download/jdk${version}u${update}-b${build_no}/OpenJDK${version}U-jdk_x64_linux_hotspot_${version}u${update}b${build_no}.tar.gz
                          tar -xzvf OpenJDK${version}U-jdk_x64_linux_hotspot_${version}u${update}b${build_no}.tar.gz -C /home/circleci
                          mv $JAVA_HOME${version}u${update}-b${build_no} $JAVA_HOME
                      else
                          echo "JDK cache hit, exiting"
                          circleci-agent step halt
                      fi
            - save_cache: *save-jdk-cache
            - slack/notify:
                  branch_pattern: develop #Only triggers on the develop branch (or tags, see below)
                  channel: ${SLACK_CHANNELID} # Environment variable in project, ID for the v6-dev-ops channel
                  event: fail #Notifies only in the event of failure
                  mentions: '@here'
                  tag_pattern: /\d+\.\d+\.\d+$/ #Tag pattern for weekly releases (also triggers on develop, see above)
                  template: basic_fail_1 #Uses built-in template, see here for more info: https://github.com/CircleCI-Public/slack-orb/wiki#templates
```

Results when job is called in Workflow: See attached screenshot
* Notice how all the steps *except* `slack/notify` occur as expected, without any warning or error related to Slack
**Screenshot**
<img width="1518" alt="Screen Shot 2021-04-28 at 7 45 01 PM" src="https://user-images.githubusercontent.com/24556426/116489275-3da9e700-a85a-11eb-845c-7b96b064676e.png">

Any help or info would be  appreciated, thanks!

**Comment by rattrayalex** [comment]
You might try `ignore_errors: false`

**Comment by HennaAbbas** [comment]
@jon-flowers I tried to recreate this issue locally using [version 4.6.1 of the slack orb 
](https://circleci.com/developer/orbs/orb/circleci/slack?version=4.6.1) and the `cimg/base:2020.01` image and was not able to do so. Are you still seeing this issue? If so, can you please share a build link, the image you are using and version of slack orb you a using?

**Comment by jon-flowers** [comment]
Hi @HennaAbbas , 
It looks like with the newer version I am no longer seeing the problem.  Thanks for checking!  I will make sure to get our versions updated.
