### ISSUE TITLE
Access to a Changelog

### ISSUE THREAD

**Issue by dynamike** [CircleCI-Public/slack-orb#268]
## Describe Request:

Is it possible to get access to a Changelog for releases? 

## Examples:

Anything in Github Releases or even a CHANGELOG.md would suffice. 

## Supporting Documentation Links:

**Comment by sibelius** [comment]
any progress on this?

**Comment by pas256** [comment]
@iynere I would recommend using https://cli.github.com/

Whenever you make a tag for a new release (like you are now), use:

    gh release create 4.5.1

... and populate the changes log from the commit log. It's the easiest thing I have found.

**Comment by EricRibeiro** [comment]
We are investigating the best way to add changelogs to all official orbs. This effort will require a few changes to the deployment strategy currently handled by the [orb tools orb](https://github.com/CircleCI-Public/orb-tools-orb) and is already in the backlog for the next major release.

I'll keep this issue open to notify everyone watching when this feature is out.
