### ISSUE TITLE
Getting invalid_attachments error when posting message to Slack

### ISSUE THREAD

**Issue by nikhilkumarbol** [CircleCI-Public/slack-orb#283]
## What happened: Getting `invalid_attachments` error on trying to send a lengthy message to slack

We send a changelog message calculated in the CI to Slack. In this way, it worked perfectly till now. Today, I saw a message that was the longest ever we posted and it failed. CircleCI says that it did receive exit code 0, but the message is not posted. It shows the following and stops, and is shown as success - 

```
{
  "ok": false,
  "error": "invalid_attachments"
}
```

We also tried orb version 4.4.2, but it is still the same even there. Also, it is nowhere mentioned about any message limits in this orb. So I'm guessing it should work.

The following is what we got - 

<img width="437" alt="Screenshot 2021-06-25 at 5 30 00 PM" src="https://user-images.githubusercontent.com/58935365/123422020-3d6c6480-d5db-11eb-99da-e678a74b1438.png">

I tested the message limits by trial and error and found that it is failing if the character count exceeds 2994.

Are there any limits on the character count in a message that is sent to Slack? Any idea about what's going wrong?

Thank you in advance.

**Comment by EricRibeiro** [comment]
Hi @nikhilkumarbol, exciting observation!

I went through Slack's documentation, and your hypothesis is on the spot! Extracted from the [rate limits section](https://api.slack.com/docs/rate-limits#posting_messages):

> The message server will disconnect any client that sends a message longer than 16 kilobytes. This includes all parts of the message, including JSON syntax, not just the message text. Clients should limit messages sent to channels to 4000 characters, which will always be under 16k bytes even with a message comprised solely of non-BMP Unicode characters at 4 bytes each. If the message is longer a client should prompt to split the message into multiple messages, create a snippet or create a post.

This 4000 characters limit is also mentioned in the[ API documentation](https://api.slack.com/methods/chat.postMessage#formatting):

> For best results, limit the number of characters in the text field to 4,000 characters. Ideally, messages should be short and human-readable. Slack will truncate messages containing more than 40,000 characters.

In your scenario, you are not exceeding the character count, so my assumption is that your payload size goes above their limit. Can you try checking it?

**Comment by EricRibeiro** [comment]
I reproduced this to some extent [here](https://app.circleci.com/pipelines/github/CircleCI-Public/slack-orb/1093/workflows/fb598d10-4455-499b-ae81-0615d2cfdaac/jobs/4217/parallel-runs/0/steps/0-102). I'm using blocks instead of attachments, hence the different message. 

Interestingly the message returned by the API in my test said:

> [ERROR] must be less than 3001 characters

So their docs might be outdated. Unfortunately, we can do nothing from the orb perspective, so I'm closing this issue.
