### ISSUE TITLE
Empty slack channel does not raise error, even with `ignore_errors: false`

### ISSUE THREAD

**Issue by rattrayalex** [CircleCI-Public/slack-orb#284]
## Orb version:

4.4.2

## What happened:

I had a bug in my bash that resulted in the `channel` parameter receiving an empty value. 
The job was marked as succeeded, but no slack message was sent (not even to our default channel).
No warnings were printed to the console.

## Expected behavior:

Some combination of the below (ideally all):

1. echo a warning when `channel` parameter is used but empty. 
2. raise an error when `channel` parameter is empty and `ignore_errors` is `false`.
3. send to default channel when `channel` parameter is empty.

**Comment by EricRibeiro** [comment]
Thank you for creating this issue @rattrayalex!

We have a check in place for the channel parameter [here](https://github.com/CircleCI-Public/slack-orb/blob/master/src/scripts/notify.sh#L127). I tried replicating the issue you described, and [I got an error](https://app.circleci.com/pipelines/github/CircleCI-Public/slack-orb/1021/workflows/72015845-32a2-4436-a67b-2b1a81c44100/jobs/3905) as expected. I used the channel parameter with an empty value.

Can you confirm if you still see this behaviour in the most up-to-date orb version? Also, can you send a snippet with what you are doing or the pipeline link?

**Comment by rattrayalex** [comment]
Thanks @EricRibeiro ! I don't have access to the relevant code anymore, so I can't retry myself, but looking at the code and repro case you posted I believe this to be resolved. Thank you!
