### ISSUE TITLE
Add "mentions" to the basic_success_1 template.

### ISSUE THREAD

**Issue by ozomer** [CircleCI-Public/slack-orb#285]
"Mentions" is useful not only in fail cases, but also in success cases.

Another option is to create a different `basic_success_2` template, or `basic_success_with_mentions_1` template.

**Comment by GarvitSinghal47** [comment]
ozomer, i will like to work on it can you plz explain some more detail about it

**Comment by HennaAbbas** [comment]
@ozomer you can use the mentions parameter with the `basic_success_1` template. What slack orb version are you using? Can you try using the latest version: 4.5.2 ?

Additionally, you can use the [block kit builder](https://app.slack.com/block-kit-builder/) to create your own custom template.

**Comment by HennaAbbas** [comment]
The functionality was added in the following PR:  [Add mentions to basic_success_1.json #286](https://github.com/CircleCI-Public/slack-orb/pull/286).
