### ISSUE TITLE
Environment variables for the context are not mentioned anywhere

### ISSUE THREAD

**Issue by mimozell** [CircleCI-Public/slack-orb#288]
## Describe Request:
The orb does not explain what kinds of environment variables the circle context should contain. There should be some mention of what needs to be set up in relation to auth at the least. The only ones I see without digging into the source are: SLACK_DEFAULT_CHANNEL and SLACK_PARAM_MENTIONS.

## Supporting Documentation Links:

**Comment by gmemstr** [comment]
@mimozell [The wiki contains a page for this](https://github.com/CircleCI-Public/slack-orb/wiki/Setup), and the documentation generated on the [orb's registry page](https://circleci.com/developer/orbs/orb/circleci/slack) also mentions them. How could we better document this?

**Comment by mimozell** [comment]
Yeah, I found them in the wiki page, but I think the orb page should also be explicit about them. If you look up SLACK_ACCESS_TOKEN in the page, for example, you see that it is buried in the source code, but not mentioned anywhere else. Usually env vars are specified separately or as parameters to jobs, in my experience.

**Comment by Jaryt** [comment]
@gmemstr Seems to me that this could be included in the quick start section. Perhaps that should be procedure - just wouldn't have fancy graphics like the wiki. Not sure if adding extra steps to that section is possible.
