### ISSUE TITLE
slack/notify fails with debian repo error

### ISSUE THREAD

**Issue by nojunpark** [CircleCI-Public/slack-orb#292]
## What happened:

The slack notify definition we have in our config.yml for the circleci setup worked well for past months, but starting this week it started to fail with the following error:
```
Posting Status
Checking For JQ + CURL: Debian
E: Repository 'http://security.debian.org/debian-security buster/updates InRelease' changed its 'Suite' value from 'stable' to 'oldstable'
E: Repository 'http://deb.debian.org/debian buster InRelease' changed its 'Suite' value from 'stable' to 'oldstable'
E: Repository 'http://deb.debian.org/debian buster-updates InRelease' changed its 'Suite' value from 'stable-updates' to 'oldstable-updates'

Exited with code exit status 100
CircleCI received exit code 100
```

## Expected behavior:
slack/notify executes and the slack channel received notification

## Additional Information:
Started failing on Monday, August 16th 2021
This also happens with the latest orb, 4.4.2

**Comment by KyleTryon** [comment]
Hello @nojunpark could you try running this command prior to slack/notify? `apt-get update --allow-releaseinfo-change`
Also, what executor are you using?

**Comment by nojunpark** [comment]
> Hello @nojunpark could you try running this command prior to slack/notify? `apt-get update --allow-releaseinfo-change`
> Also, what executor are you using?

Thanks will try, we have been always using the `minimal executor`
