### ISSUE TITLE
Message containing GitHub PR number

### ISSUE THREAD

**Issue by maskedjellybean** [CircleCI-Public/slack-orb#293]
## Describe Request:

Is it possible for the Slack message to contain the GitHub Pull Request number? If so, how? 

## Supporting Documentation Links:

**Comment by HennaAbbas** [comment]
Yes, you can use the CIRCLE_PULL_REQUEST [environment variable](https://circleci.com/docs/2.0/env-vars/#built-in-environment-variables) and a [custom slack message ](https://github.com/CircleCI-Public/slack-orb/wiki#custom-message-template). You can also write a script that extracts the PR number from the CIRCLE_PULL_REQUEST environment variable (URL to PR) and [set the PR_Number as a environment variable in a shell script] (https://circleci.com/docs/2.0/env-vars/#setting-an-environment-variable-in-a-shell-command)

**Comment by EricRibeiro** [comment]
@HennaAbbas did a fantastic job explaining how to achieve what the issue's author needs, so I'm closing this issue.

@maskedjellybean, if you are still having problems getting a custom template with the PR number on it, please open another issue and we will be happy to help!
