### ISSUE TITLE
How to send message to private channel?

### ISSUE THREAD

**Issue by caleb15** [CircleCI-Public/slack-orb#295]
I tried it but got:

```
Slack API returned an error message:
"channel_not_found"
```

**Comment by pushyka** [comment]
Make sure you have spelled the name correctly / try with the channel id instead.
Also, you will need to add the app to the private channel (under integration settings) (but if that was the problem in this case you would get a different error: 

```
Slack API returned an error message:
"not_in_channel"
```

**Comment by PetriPockethunt** [comment]
I have similar experience, posting messages in private group is not working. Posting messages to public channels is working.
I tested with two channel configuration
` - slack/notify:
       channel: 'publicId, privateId'
`

Error message for private group is 

> The response from the API call to slack is : {"ok":false,"error":"channel_not_found","warning":"missing_charset","response_metadata":{"warnings":["missing_charset"]}}

Response for the public channel is

> The response from the API call to slack is : {"ok":true, etc...

App has been added to both channels and it has following permissions:

Bot Scopes
chat:write
chat:write.public
files:write
groups:write

User Scopes
chat:write
files:write
groups:write

Any thoughts what I should try next?

**Comment by EricRibeiro** [comment]
Hey, @caleb15 and @PetriPockethunt 👋 

I replicated your issue [here](https://app.circleci.com/pipelines/github/CircleCI-Public/slack-orb/1095/workflows/1307c961-104c-43e1-a252-073695b0a326/jobs/4226/parallel-runs/0/steps/0-117) and learned that @pushyka was right on the spot! To have the slack orb working with private channels, you need to add your app to said channel. From Slack's [documentation](https://api.slack.com/methods/chat.postMessage#channels__post-to-a-multi-person-direct-message):

> As long as the **authenticated user is a member of the multi-person direct message** (AKA "private group" or MPIM), you can pass the group's ID (G012AC86C), and the message will be posted to that group.

Try adding your app in the channel for which you pass the ID, and it should work. I got a [successful response](https://app.circleci.com/pipelines/github/CircleCI-Public/slack-orb/1095/workflows/2c11ded5-fcb9-425e-a9da-11805d333fee/jobs/4242/parallel-runs/0/steps/0-117) from the Slack API after doing so.

**Comment by EricRibeiro** [comment]
@caleb15 and @PetriPockethunt, I'll close this issue since it's stale.

Feel free to post your updates. I'll be happy to re-open it should you still need it.
