### ISSUE TITLE
Example templates from this repo do not work with Kite Builder

### ISSUE THREAD

**Issue by swiknaba** [CircleCI-Public/slack-orb#297]
## What happened:

I wanted to extend the existing basic template, I found the code for those here: https://github.com/CircleCI-Public/slack-orb/tree/master/src/message_templates

When I paste the JSON into the kite builder: https://app.slack.com/block-kit-builder, there are multiple validation errors.

## Expected behavior:

I'd expect, that I can use those templates with the Kite builder to extend them to my liking.

## Additional Information:

![image](https://user-images.githubusercontent.com/20702503/133297993-448a3885-5683-4f01-9972-50c27bec1886.png)

**Comment by EricRibeiro** [comment]
Hi @swiknaba, thank you for bringing this issue to our notice!

What is happening here is that we need to have one extra `text` [property](https://github.com/CircleCI-Public/slack-orb/blob/master/src/message_templates/basic_success_1.json#L2) at the root level for internal use. However, as you noticed, this line is not valid from the Block Kit Builder perspective.

With your opening this issue, we realize this can confuse users looking to customize existing templates. We will look into removing the problematic line from them to avoid further confusion. 

In the meantime, you can safely remove it from your custom template in the Block Kit Builder. Do bear in mind that you might see other validation issues with [lines containing environment variables](https://github.com/CircleCI-Public/slack-orb/blob/master/src/message_templates/basic_success_1.json#L65). This doesn't mean your template won't work, though.

I'll close this issue but feel free to reopen it if you still have problems.
