### ISSUE TITLE
Preventing debian repo error by passing `--allow-releaseinfo-change` to apt-get

### ISSUE THREAD

**Issue by tzimmermann** [CircleCI-Public/slack-orb#300]
I would like to suggest a more general solution to the issue https://github.com/CircleCI-Public/slack-orb/issues/292.

We are using the slack/notify orb for a couple of different jobs with different executors.
Some of these are running as root (for example [this one from cypress](https://github.com/cypress-io/cypress-docker-images/blob/master/browsers/node14.15.0-chrome86-ff82/Dockerfile)) and some are not.

Currently, there is no easy way to get around the error in https://github.com/CircleCI-Public/slack-orb/issues/292 except for running `apt-get update --allow-releaseinfo-change` with and without `sudo` prefix in several places.

What about simply adding `--allow-releaseinfo-change` to the `apt-get update` command inside the notify script here?
That should solve our issues and prevent anyone else hitting this in the future and needing to work around it.

https://github.com/CircleCI-Public/slack-orb/blob/9650da83d92512c1a0e8be50e7482a6a7f6bbcca/src/scripts/notify.sh#L71

**Comment by EricRibeiro** [comment]
Thanks for opening this issue, @tzimmermann.

You have a good point. Another solution is to curl jq from their GitHub repository.

I'll run a few tests to check which strategy makes more sense and open a PR shortly.
