### ISSUE TITLE
Support "unfurl_links": false to declutter notifications with URLs

### ISSUE THREAD

**Issue by klaukl** [CircleCI-Public/slack-orb#302]
## Describe Request:
Allow "unfurl_links": false doesn't seem to be supported. Apparently it needs to be passed as a param when sending the message. 

## Examples:
I've tried putting it in the block templates in the text but api errors when sending using slack orb. Probably need a new param to pass. 

## Supporting Documentation Links:
https://api.slack.com/methods/chat.postMessage
unfurl_links | boolean | Pass true to enable unfurling of primarily text-based content

**Comment by EricRibeiro** [comment]
@klaukl, you can set optional arguments by adding them to the root of your template body. To alter the `unfurl_links` optional argument, you need create a [custom](https://github.com/CircleCI-Public/slack-orb#custom-message-template) or [dynamic](https://github.com/CircleCI-Public/slack-orb/wiki/Dynamic-Templates) template with:

```
{
  "text": "CircleCI job succeeded!",
  "blocks" [...],
  "unfurl_links": false
}
```

Can you please try this and let me know how it goes?

**Comment by EricRibeiro** [comment]
@klaukl,  I'll close this issue since it's stale, but I'll be happy to re-open it should you need it.

**Comment by matthewmcvickar** [comment]
@EricRibeiro Would you consider adding this to the documentation for the Slack orb? I tried to find out how to do this and it took me a while to find the answer in this closed issue. :)
