### ISSUE TITLE
Send only final status of the workflow

### ISSUE THREAD

**Issue by villesau** [CircleCI-Public/slack-orb#305]
## Describe Request:

Using parallel jobs is the recommended way to speed up the build process. However, currently the slack orb is unusable when using them. The slack orb will pollute the slack channel so badly that the channel will become just noise. For example we have all the independent checks in parallel jobs which would result way over 10 status messages for _every built PR commit_. Multiply that by the amount of PRs and then by the amount of commits to those PRs and you get countless of amounts of useless slack notifications, over 10x more than desired. If you have 10 pull requests a day, 10-20checks and 3 commits for each, you get 300-600 messages per day to slack with current method, when the desired amount would be 10 x 3 = 30.

Thus it would be essential to have trigger for the overall workflow status message.

## Supporting Documentation Links:

https://github.com/CircleCI-Public/slack-orb/wiki/FAQ

See the second FAQ question. In any other CI system, like Jenkins for example, that is possible, and practically the only proper way to report status from CI to Slack.

**Comment by gmemstr** [comment]
Ideally a seperate job is used to report the status in the case of parallel steps. If we opted to send a notification only on one job, we'd introduce a race condition that would assume all the jobs complete at the same time with the same result.

With that said, we're working closely with the team responsible for Webhooks (https://circleci.com/docs/2.0/webhooks/) to hopefully address such an issue, so stay tuned :)

**Comment by villesau** [comment]
How would that work in following case:

```
Job 1 ─────┐
           │
Job 2 ─────┤
           │
Job 3 ─────┴─────► Any failed or all succeeded



Job 1 ─────┐
           │
Job 2 ─────┤
           │
Job 3 ─────┴─────► Deploy ────► Deploy succeeded or any failed
```

In the above case the first diagram happens when running agains pull request. The second diagram when running on master. Both defined in the same file. We would want to report as soon as we know that the build will fail(any job has failed), and immediately after we know that the whole pipeline has succeeded, but we don't need more than one message per pipeline. All the Jobs are run in parallel. Some of them build, some of them run linting, some tests etc.

**Comment by EricRibeiro** [comment]
Hi @villesau. Unfortunately, this can't be resolved with the orb. 

This will require an alternative solution such as a webhook-based slack integration. We are still investigating if it can be done and how it would work.

Considering there's no way around that with orbs, I'll close this issue.

**Comment by villesau** [comment]
@EricRibeiro can you then take the feedback to the correct team? The notification workflow I described is the most basic I've ever setup before so it's a massive bummer that SaaS based CI that's sole purpose is to support CI workflows cannot stretch to it.

**Comment by KyleTryon** [comment]
@villesau this is the correct team 👍.

Getting the "final" status of a workflow is not possible exclusively within the abilities of the orb. It is possible to replicate somewhat similar functionality, but the setup may be different for different users and will require additional setup beyond the orb.

If you have a setup such as this:
```
Job 1 ─────┐
           │
Job 2 ─────┤
           │
Job 3 ─────┴─────► Deploy ────► Deploy succeeded or any failed
```

Deploy can fire a notification but, if any job 1-3 fails, deploy will never have the chance to run. This is mentioned in our Wiki FAQ in a little more detail: https://github.com/CircleCI-Public/slack-orb/wiki/FAQ

Orbs, as "packaged config", which is not code itself, simply does not have the ability to support this style of integration. 

We do now have Webhooks, which can be ingested, though we do not have a slack connector for webhooks yet as webhook based integrations have a lot less customizability than you get from this orb. Please let us know if you would be interested in webhook based notifications.

We hope to in the future build an alternative bot-based integration which will land somewhere in the middle of these two solutions.

**Comment by villesau** [comment]
Ok, that's good to hear! My biggest wishes are: I get notified as fast as the build is failing, and will not be spammed with any of the other statuses, except potentially when the failing build has finished. I also want to know immediately when the build has succeeded. And I want the slack notification to tag the merger in the notification. And as said, the final step (deploy) is there when merging in master, but it's not there when building pull request.

Would also make sense to get private messages of the pull request builds. And would make sense to have possibility to write own messages for the notifications, like links to correct dashboards and such.

This would give just the right amount of information and the most timely notifications possible to react fast. And this is the notification workflow I've always before built and seen when working with Jenkins.

**Comment by jmreicha** [comment]
Running into this situation as well. Am I understanding correctly, there is not currently any way to report the final status of the workflow to e.g. a Slack channel with the orb or with a webhook?

**Comment by EricRibeiro** [comment]
> there is not currently any way to report the final status of the workflow to e.g. a Slack channel with either the orb or a webhook?

@jmreicha, as Kyle mentioned above, it is impossible to do it with the orb. However, we can implement a webhook-based solution to cover this use case if we see enough traction.

**Comment by jmreicha** [comment]
Not sure how to lobby for this feature but it would definitely be useful.

**Comment by asnider93** [comment]
Heya @EricRibeiro @KyleTryon just following up since it's been a few months since the last update :)

As it stands if you do something like below 

`workflows:
  build:
    jobs:
      - build_branch:
          filters:
            branches:
              only: /.*/
            tags:
              ignore: /.*/
      - build_tag:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /.*/
      - notify:
          context: slackerino
          requires:
            - build_tag
            - build_branch`

Slack will only notify on a success, because both build jobs need to succeed in order for the notify job to work. If one of those jobs fail, no notification is sent. There's no `or` logic that can be used to only have it dependent on one and maybe submit a fail for the other? Just using webhooks instead of orbs? Or something as is stated here: https://support.circleci.com/hc/en-us/articles/360047082992-Send-slack-notification-at-end-of-workflow which I assume is what OP was referring to because it seems like this would cause an immense amount of notifications.

**Comment by villesau** [comment]
@gmemstr @EricRibeiro any movement with this?

**Comment by rdhelms** [comment]
@gmemstr @EricRibeiro @KyleTryon We also would love to have a way to get one Slack notification per workflow telling us whether the whole workflow succeeded, or whether _any_ part of the workflow failed. Currently we have a ton of `slack/notify` steps scattered all over our config.

If there's a way to do this with webhooks, even without the orb, I'd love to hear what others have come up with.

@villesau Did you come up with a satisfactory way to accomplish this?

**Comment by villesau** [comment]
@rdhelms nope :/ The moment some CI SaaS solves that we'll likely switch over to that one.

**Comment by rdhelms** [comment]
@villesau We ended up completely removing this orb and switched to using the Workflow Completed webhook. We setup an AWS Lambda to receive the webhook payload and then send a Slack notification using a custom Slack app with its own incoming webhook. Not sure if it'll be useful to anyone else, but here's our lambda handler to process the circleci payload and format the slack notification:

```
const https = require('https')

/**
 * Receives "Workflow Completed" webhook events from CircleCI and sends Slack notifications
 */
exports.circleWorkflowWebhook = async event => {
    const reqBody = JSON.parse(event.body)
    const projectName = reqBody?.project?.name
    const buildNum = reqBody?.pipeline?.number
    const workflowName = reqBody?.workflow?.name
    const workflowUrl = reqBody?.workflow?.url
    const status = reqBody?.workflow?.status
    const triggerType = reqBody?.pipeline?.trigger?.type
    const branch = reqBody?.pipeline?.vcs?.branch
    const authorName = reqBody?.pipeline?.vcs?.commit?.author?.name || reqBody?.pipeline?.vcs?.commit?.committer?.name
    const commitMessage = reqBody?.pipeline?.vcs?.commit?.subject
    const repoUrl = reqBody?.pipeline?.vcs?.origin_repository_url
    const commitHash = reqBody?.pipeline?.vcs?.revision
    const statusIcon = status === 'success' ? ':white_check_mark:'
        : status === 'failed' ? ':x:'
        : ':heavy_multiplication_x:'

    const postData = JSON.stringify({
        "text": `${statusIcon} Run ${workflowName} #${buildNum} of the ${projectName} project - ${status}`,
        "blocks": [
            {
                "type": "section",
                "text": {
                    "type": "mrkdwn",
                    "text": `${statusIcon} Run *${workflowName}* <${workflowUrl}|#${buildNum}> of the <${repoUrl}|${projectName}> project - *${status}*`
                }
            },
            {
                "type": "section",
                "text": {
                    "type": "mrkdwn",
                    "text": `${commitMessage || triggerType} (<${repoUrl}/commit/${commitHash}|${commitHash.slice(0, 7)}>)`
                }
            },
            {
                "type": "context",
                "elements": [
                    {
                        "type": "mrkdwn",
                        "text": `${authorName ? `${authorName} | ` : ''}${branch}`
                    }
                ]
            }
        ]
    })
    const options = {
        method: 'POST',
        headers: {
           'Content-Type': 'application/json',
           'Content-Length': postData.length,
        }
    }

    try {
        const result = await new Promise((resolve, reject) => {
            let body = ''
            const req = https.request(process.env.SLACK_WEBHOOK_URL, options, res => {
                res.on('data', chunk => {
                    body += chunk
                })
                res.on('end', () => {
                    console.log(body)
                    resolve(body)
                })
            })
    
            req.on('error', (err) => {
                console.error(err)
                reject(err)      
            })
                
            req.write(postData)
            req.end()
        })
        return { statusCode: 200, body: JSON.stringify(result) }
    } catch (err) {
        return { statusCode: 500, body: err.toString() }
    }
}

```

**Comment by anudeepanu** [comment]
Thank you @rdhelms, I have implemented the same
