### ISSUE TITLE
bring back compact templates

### ISSUE THREAD

**Issue by wyardley** [CircleCI-Public/slack-orb#309]
## Describe Request:
Please bring back the much more compact output format of the 3.x release's templates.

## Supporting Documentation Links:

**Comment by gmemstr** [comment]
Can you provide an example? While there's nothing stopping you from providing your own template, it may be worth including one in the base template package.

**Comment by wyardley** [comment]
So, the example in the README for the last 3.x tag:
https://github.com/CircleCI-Public/slack-orb/tree/v3.4.2

This is way more compact than the messages from the new version:
![image](https://user-images.githubusercontent.com/10714426/144280970-4efd8482-76dc-4f4c-ac08-1e67a901aa83.png)
![image](https://user-images.githubusercontent.com/10714426/144281071-a94b91c9-284a-473b-b7c6-772fa3d05573.png)
also, the fields included were, IIRC, more customizable, i.e.,g you could include or not include the job number etc.

To me, this is a better basic look for the "basic" success / failure template, vs something like this (even ignoring the junk mentioned in #310)
![image](https://user-images.githubusercontent.com/10714426/144281223-eea89e66-f6c8-48dc-9016-fa9d890de6ad.png)

Agreed that custom templates would work, but I don't really want to either wrap this orb with my own orb, or include inline templates in multiple projects for something simple.

**Comment by wyardley** [comment]
I think a couple of the issues are due to
1) using the new "blocks" style composition. While I know it's "legacy", using an attachment with blocks inside would keep the old look feel (and the color status information on the left)
2) Seems like the old setup made it easier to have certain fields be optional / suppressed.

I'm guessing I will end up needing to do custom templates, but FWIW, IMO the old ones were both more compact and better looking.

**Comment by EricRibeiro** [comment]
> using the new "blocks" style composition. While I know it's "legacy", using an attachment with blocks inside would keep the old look feel (and the color status information on the left)

You are correct that using an attachment inside blocks would give you the old look and feel; however, you can get some extent of similarity with the new message composition:

```JSON
{
	"blocks": [
		{
			"type": "header",
			"text": {
				"type": "plain_text",
				"text": ":tada: A job has succeeded! ${SLACK_PARAM_MENTIONS}",
				"emoji": true
			}
		},
		{
			"type": "section",
			"fields": [
				{
					"type": "mrkdwn",
					"text": "*Project:*\n$CIRCLE_PROJECT_REPONAME"
				},
				{
					"type": "mrkdwn",
					"text": "*Job Number:*\n$CIRCLE_BUILD_NUM"
				}
			]
		},
		{
			"type": "actions",
			"elements": [
				{
					"type": "button",
					"text": {
						"type": "plain_text",
						"text": "View Job"
					},
					"url": "${CIRCLE_BUILD_URL}"
				}
			]
		}
	]
}
```

Unfortunately, there is [no equivalent](https://api.slack.com/messaging/attachments-to-blocks#direct_equivalents) for the colour status information. If that's a must for you, you need to stick with [attachments](https://api.slack.com/messaging/composing/layouts#attachments), but, as you know, they are legacy and can [change in the future](https://api.slack.com/messaging/composing/layouts#when-to-use-attachments).

> Seems like the old setup made it easier to have certain fields be optional / suppressed.

The old setup had command parameters that allowed the user to customize the notification to some extent (e.g. [job number](https://github.com/CircleCI-Public/slack-orb/blob/v3.4.2/src/commands/notify.yml#L64)). While I agree that it is easier to use for simple use-cases, it doesn't allow for the flexibility that version 4 brought with the introduction of the templates. With custom templates, you can create whatever design is supported by Slack with as much information you desire or need, without the limitations of the command parameters.

> Agreed that custom templates would work, but I don't really want to either wrap this orb with my own orb, or include inline templates in multiple projects for something simple.

I believe [Context](https://github.com/CircleCI-Public/slack-orb/wiki/Reuse-Custom-Templates) fits very nicely here. You won't have to fork this orb nor directly include inline templates in all your projects. You can find more details in the aforementioned link, but the gist is that you write the template once, save it in a context, and reference it in whatever project you need as an environment variable. Give it a shot!

I hope this works for you! As Slack discourages its use, we won't include templates with attachments in the orb.
