### ISSUE TITLE
Extra literal \n in output

### ISSUE THREAD

**Issue by wyardley** [CircleCI-Public/slack-orb#310]
## Orb version:
4.5.0

## What happened:
basic_success_1 and basic_failure_1 templates have extra literal `\n` characters in messages

![image](https://user-images.githubusercontent.com/10714426/144132398-4f1133c0-255e-49c2-baf9-9724605ae125.png)

<img width="669" alt="Screen Shot 2021-11-30 at 1 41 07 PM" src="https://user-images.githubusercontent.com/10714426/144132809-d8cfdd9b-07c6-433e-b899-79a224aab148.png">

**Comment by ueokande** [comment]
maybe It occur by https://github.com/CircleCI-Public/slack-orb/pull/277

**Comment by wyardley** [comment]
Yeah, #277 is the one I thought would fix it (some of those did exist in 4.4 as well), but seems to have made it worse, rather than better.

**Comment by KyleTryon** [comment]
Resolved in #314
