### ISSUE TITLE
local run causes "invalid_blocks" error

### ISSUE THREAD

**Issue by oliver-subskribe** [CircleCI-Public/slack-orb#312]
## Orb version:

4.4.4

## What happened:

When the job that uses the slack/notify runs inside circleci, no problem
When the same job runs local using the circleci CLI, the job succeeds but the orb shows an error: 
```
circleci config process .circleci/config.yml > /tmp/cci-local.yml
circleci local execute -c /tmp/cci-local.yml --job deploy-me --revision $GIT_HASH -e REPO_URI=... \
      -e SLACK_ACCESS_TOKEN=xoxb-... \
      -e AWS_ACCESS_KEY_ID=... -e AWS_SECRET_ACCESS_KEY=...

Docker image digest: sha256:...
====>> Spin up environment
Build-agent version  ()
System information:
 Server Version: 20.10.8
 Storage Driver: overlay2
  Backing Filesystem: extfs
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Kernel Version: 5.10.47-linuxkit
 Operating System: Docker Desktop
 OSType: linux
 Architecture: x86_64

...

# Will not run if sourced from another script.
# This is done so this script may be tested.
ORB_TEST_ENV="bats-core"
if [ "${0#*$ORB_TEST_ENV}" = "$0" ]; then
    CheckEnvVars
    . "/tmp/SLACK_JOB_STATUS"
    ShouldPost
    InstallJq
    BuildMessageBody
    PostToSlack
fi

Posting Status
Checking For JQ + CURL: Debian
Sending to Slack Channel: deployment-notifications
Slack API returned an error message:
"invalid_blocks"

View the Setup Guide: https://github.com/CircleCI-Public/slack-orb/wiki/Setup
Success!
```

## Expected behavior:

I'm glad that slack/notify does not notify slack channel when run from local circleCI CLI, BUT there should be no error message: 
- the orb actually succeeds (job says Success!)
- there may be situations (like if custom template is used) where it would succeed slack notification, which would be annoying for local run

**Comment by KyleTryon** [comment]
Hello @oliver-subskribe,

Orbs are not officially supported by the local CircleCI CLI, but I am surprised in this case that it did not work. We may not be able to resolve this, as it is likely not directly related to the orb but may be with the CLI. Out of curiosity could you share the job definition from your config with the docker image used?

**Comment by oliver-subskribe** [comment]
I think mostly the error message might have just been unclear or misleading. because works fine now, and you might be right I think it was something related to missing SLACK_ACCESS_TOKEN or something, sorry I cannot remember the details from 6 weeks ago :> The error was just unclear.
