### ISSUE TITLE
Checking For JQ + CURL: Debian

### ISSUE THREAD

**Issue by maelfosso** [CircleCI-Public/slack-orb#315]
## Orb version:
slack@4.5.1

## What happened:

Posting Status
Checking For JQ + CURL: Debian
parse error: Expected separator between values at line 5, column 14
parse error: Expected separator between values at line 5, column 14

Exited with code exit status 4
CircleCI received exit code 4

## Expected behavior:

NO Error

## Additional Information:
Here is the repo https://github.com/maelfosso/cdond-c3-projectstarter

**Comment by EricRibeiro** [comment]
Thank you for opening this issue, @maelfosso. 

I can see that in your [most recent pipeline](https://app.circleci.com/pipelines/github/maelfosso/cdond-c3-projectstarter/81/workflows/be0fa55c-49af-4a01-a1cb-f65822ae80a2) your [scan-backend](https://app.circleci.com/pipelines/github/maelfosso/cdond-c3-projectstarter/81/workflows/be0fa55c-49af-4a01-a1cb-f65822ae80a2/jobs/574) job is passing. Was your problem resolved?

**Comment by EricRibeiro** [comment]
Hey @maelfosso, you are still experiencing this issue, please open an issue with an example of your notify command.
