### ISSUE TITLE
Breaking change in v4.6.0

### ISSUE THREAD

**Issue by sarahhodne** [CircleCI-Public/slack-orb#323]
## Orb version:

4.6.0 and 4.6.1

## What happened:

https://github.com/CircleCI-Public/slack-orb/commit/cdba2d85c202afc061cf836a8e357ef9111e89b0 appears to have added a dependency on `sudo` where there wasn't one before, so when trying to upgrade from 4.5.3 to 4.6.1 builds are now failing with:

```
environment: line 152: sudo: command not found
```

I suspect this is because we're using images without sudo installed on them.

## Expected behavior:

Builds continue to work without changes on a minor version upgrade.

## Additional Information:

The image and repo are all private, feel free to ping me on Slack if you need links to them.

**Comment by KyleTryon** [comment]
@sarahhodne Thank you for sharing. This should be a fairly simple fix. Is the image you were using public? It would be helpful to us perhaps to use this image in our testing as example of an image without sudo installed.

**Comment by sarahhodne** [comment]
It's `alpine:3.14` (with bash, build-base, curl, git, jq, make, openssh, openssh-keygen, python3, python3-dev, py3-pip).

**Comment by dincho** [comment]
Wow, just in time! I just got stuck with the same issue yesterday, thanks for fixing it! 🥳

**Comment by sarahhodne** [comment]
Looks like this resolved it for us, thank you!
