### ISSUE TITLE
slack/notify on fail?

### ISSUE THREAD

**Issue by ahtutejlo** [CircleCI-Public/slack-orb#33]
How to run slack/notify on fail builds only?
I can run it in slack/status but it is not possible to set a custom message there.

**Comment by cayter** [comment]
Any plan to add `when: <on_fail|on_success>` support?

**Comment by KyleTryon** [comment]
Hello @cayter 

Would the status command not work for you? https://github.com/CircleCI-Public/slack-orb#status

**Comment by cayter** [comment]
@KyleTryon Nope as we needed to support custom message.

**Comment by lokst** [comment]
Closing this issue as it looks like it is already resolved by https://github.com/CircleCI-Public/slack-orb/pull/37
