### ISSUE TITLE
`debug` Mode always enabled, `mktemp` always placing files in `working_directory`

### ISSUE THREAD

**Issue by AlexanderMann** [CircleCI-Public/slack-orb#338]
## Orb version:

`slack: circleci/slack@4.8.3`

## What happened:

- `mktemp -d` is not using the standard `/tmp` but instead the current working directory. This makes things like `checkout` _reallllll_ unhappy
- I _think_ your default `debug` flag isn't working like you want it to. I _think_ because it's a CCI boolean, it's always getting passed into your env var as `0`, or `false`, `f`, `no`, etc. I don't think it's coming in as empty string, which is what your checks for `if [ -n "${SLACK_PARAM_DEBUG:-}" ]; then` are looking for, right?
    - I can't, for the life of me, get `debug` mode to be disabled...
    - I _think_ boolean parameters are expected to be used with CCI's goofy `<< ... >>` mustache style substitution etc. As such, I _think_ they want you to not try to use it as an `env` var _<- guesstimation at best_

## Expected behavior:

- `debug` mode shouldn't be enabled all the time

## Additional Information:

- prolly too verbose above anywho
- love this orb, thanks so much for publishing it! Use it all the time!

**Comment by AlexanderMann** [comment]
Happy to make a quick PR for the above if it's helpful/welcomed! Should be a couple of lines

**Comment by EricRibeiro** [comment]
Nice catch, @AlexanderMann!

You are correct. A boolean parameter in YAML is translated to `0` or `1` when they reach the shell script. I'll push a fix for this shortly.
