### ISSUE TITLE
Slack Group Mentions

### ISSUE THREAD

**Issue by bcyip** [CircleCI-Public/slack-orb#342]
## Describe Request:
Currently only able to mention individual users.  Would like to mention a group that has multiple users in it.  This would be better as then we only have to manage groups as people come and go.  Hardcoding a person is not ideal.  

## Examples:
Each group seems to have a UUID 'S0....'
@QA-group
@Team-group

QA-group
- person 1
- person 2

## Supporting Documentation Links:

**Comment by EricRibeiro** [comment]
Hi, @bcyip 👋 

The orb already supports group mentions. You can see [here](https://github.com/CircleCI-Public/slack-orb/blob/master/.circleci/test-deploy.yml#L30) and [here](https://github.com/CircleCI-Public/slack-orb/blob/master/.circleci/test-deploy.yml#L41) that we mention the group `orbs` in the integration tests.

Are you getting some sort of error when you try it?

**Comment by EricRibeiro** [comment]
Hi, @bcyip 👋 

The orb already supports group mentions. You can see [here](https://github.com/CircleCI-Public/slack-orb/blob/master/.circleci/test-deploy.yml#L30) and [here](https://github.com/CircleCI-Public/slack-orb/blob/master/.circleci/test-deploy.yml#L41) that we mention the group `orbs` in the integration tests.

Are you getting some sort of error when you try it?

**Comment by EricRibeiro** [comment]
I am closing the issue due to not getting further details. And as mentioned in the previous comment, the orb supports group mentions.

**Comment by TNonet** [comment]
Hi @EricRibeiro,

I am unable to mention groups. I have code that works great for `U0XXXXXXX` (users) but not `S0XXXXXXXX` (groups). It would also be nice if I could use `@here`.

**Comment by EricRibeiro** [comment]
@TNonet, can you share what version of the orb you are using? Can you also share Slack's payload when you set the `debug` parameter to `true`?

**Comment by TNonet** [comment]
Version: `circleci/slack@4.2.0`
For the payload, I am getting this error adding the `debug` option.
```
Error calling command: 'slack/notify'
Unexpected argument(s): debug
```

Does this suggest my version needs to be updated?

**Comment by EricRibeiro** [comment]
> Version: `circleci/slack@4.2.0` For the payload, I am getting this error adding the `debug` option.
> 
> ```
> Error calling command: 'slack/notify'
> Unexpected argument(s): debug
> ```
> 
> Does this suggest my version needs to be updated?

Yeah, would you mind bumping it to v4.10.1?

**Comment by TNonet** [comment]
I only see changelogs from 4.9 (https://github.com/CircleCI-Public/slack-orb/releases). Are there a list of breaking changes since 4.2 somewhere?

**Comment by EricRibeiro** [comment]
We started doing changelogs somewhat recently. Nevertheless, you should not expect breaking changes since we follow semantic versioning closely. Breaking changes would lead to a major bump, i.e. v5.x.x.

**Comment by EricRibeiro** [comment]
It's been a while since the last input here, so I'll close the issue. @TNonet, please open another issue if you still face this problem with the orb's most recent version.
