### ISSUE TITLE
Context fallback for forking workflow

### ISSUE THREAD

**Issue by veidenbaums** [CircleCI-Public/slack-orb#348]
## Describe Request:
At the moment if we try to use slack notifications by working according to the forking workflow, we are facing an issue. We have set  "slack-secrets" via context to the main organization, but the problem starts if some of the developers try to make a PR from their fork to the main repo. 
Tests are failing due to this - This build was not run because we couldn't find the "slack-secrets" context. 

As soon as the dev will set the "slack-secrets" in his profile everything will be fine, but this doesn't feel right as we want to have notifications only for the main organization's master branch, not for each PR. (This was possible before some time with webhooks) 

Maybe we are missing something?

## Examples:
Our idea is to introduce something like a fallback value from the main organization for the context so that in case the user hasn't set it in his profile, it takes it from the main repository if the user has the right permissions to access it.

**Comment by EricRibeiro** [comment]
It was fixed in #350. 

The orb version with fix is [v4.9.5](https://github.com/CircleCI-Public/slack-orb/releases/tag/v4.9.5)

**Comment by veidenbaums** [comment]
Hi!

Thanks for the update.

Just made some tests, but looks like it š still the same. On forks, we get a message that couldn't find the context although it's set for the main repo.

**Comment by EricRibeiro** [comment]
Have you set the [branch pattern parameter](https://github.com/CircleCI-Public/slack-orb/blob/master/src/jobs/on-hold.yml#L5) to `main`?

**Comment by veidenbaums** [comment]
Yes we have specified it to the main - branch_pattern: master

**Comment by veidenbaums** [comment]
Sure! 
![image](https://user-images.githubusercontent.com/28038713/167462478-4b47b183-bce3-48fc-8bf1-81bbd874fcb1.png)

In case I will set the context for the forked repo, it will work fine. At the moment the context is set only for the main repo master branch, and it also will work fine in case PR gets merged. 

We just need to solve this message that shows just a few seconds after committing, and because of that, the tests don't start for the forked repo.

**Comment by EricRibeiro** [comment]
Hi @veidenbaums, sorry for taking so long to reply.

This message doesn't originate from the orb; it stems from CircleCI before any code in the orb is executed. Therefore. It is not something that can be treated or bypassed.

A potential solution is to allow forks to read the original repo's context. You can do so by enabling the option `Pass secrets to builds from forked pull requests` in your project's advanced settings. However, enabling can cause vulnerability issues. You can read about the implications [here](https://circleci.com/docs/2.0/oss/#pass-secrets-to-builds-from-forked-pull-requests).

If you want to read more about access control to your organization's context from forks, there are [this](https://circleci.com/blog/access-control-cicd/) and [this](https://circleci.com/blog/triggering-trusted-ci-jobs-on-untrusted-forks/) blog posts. They offer a more secure approach than straight-up sharing the context with forks.

I'm closing this issue as it's not related to the slack orb per se, but if you need further help, I'll be happy to help! 😄
