### ISSUE TITLE
Add 'Fixed' as an event option

### ISSUE THREAD

**Issue by j320** [CircleCI-Public/slack-orb#349]

**Comment by KyleTryon** [comment]
Hello @j320,

I have looked into this before and there are two main reasons I would point to for making this a bit more of a complex issue we would need to solve for.

1. "Fixed" is actually hard to describe outside of a very simple workflow example such as "build, test, deploy". However, more complex pipelines can have conditionals, or even dynamic config. 
    * Even locating the "last" job to compare against may be tricky. We could simply go back one pipeline, but it may be that more than one commit by more than one person were pushed at a time. We could also filter to branch, look at the previous pipeline for that branch, and only if the job is found (its entirely possible the previous pipeline ran an entirely different set of workflows) would we consider a job for potentially being "fixed"
    * This may also be desired but worth pointing out too that this will only operate at a job level, and can not tell you the status of a workflow, as the orb runs _within_ jobs.
2. Currently, this would require that a user or machine user add their CircleCI Personal Access Token to the build as the logic would be reliant on reading from the CircleCI API.
    * It is possible in the future this will not be needed but this is mostly speculation
    * This isn't ideal for security reasons

This type of functionality will work better with Webhooks (which has other pros and cons as well) which we hope to build a bot around at some point.
