### ISSUE TITLE
Individual Mentions not working with fail template

### ISSUE THREAD

**Issue by sepiette** [CircleCI-Public/slack-orb#353]
## Orb version:
4.10.1

## What happened:
I'm trying to individually notify an eng member of a build fail based on if their commit/build causes a failure. I have tried both Slack @UserName and <@Slack_id> per the documentation, and no luck. The `SLACK_PARAM_MENTIONS` is being set correctly, but the template doesn't seem to parse and accurately tag/mention a user in slack.  Code screenshots are below
<img width="1056" alt="Screen Shot 2022-05-23 at 10 31 35 PM" src="https://user-images.githubusercontent.com/5920516/169936621-6b066248-17ce-4ab4-90d5-5437ce994e42.png">
<img width="438" alt="Screen Shot 2022-05-23 at 10 30 28 PM" src="https://user-images.githubusercontent.com/5920516/169936518-2e01ef99-3ff9-4006-8f71-3e2be2c260e2.png">
<img width="669" alt="Screen Shot 2022-05-23 at 10 32 20 PM" src="https://user-images.githubusercontent.com/5920516/169936780-9220df8e-50d7-4af3-8fd5-eb5d86a3a806.png">

**Comment by EricRibeiro** [comment]
Hi, @sepiette 👋 

Your code looks ok to me. I'm not sure what you are getting from the orb, though. Is the orb posting to slack the literal value of the variable? Is it posting `SLACK_PARAM_MENTIONS` instead of whatever it should resolve to?

**Comment by EricRibeiro** [comment]
Hi, @sepiette 👋 

Your code looks ok to me. I'm not sure what you are getting from the orb, though. Is the orb posting to slack the literal value of the variable? Is it posting `SLACK_PARAM_MENTIONS` instead of whatever it should resolve to?

**Comment by sepiette** [comment]
Hi @EricRibeiro sorry for the very delayed reply - it turns out the user ID being used was not the correct ID, so it now works. However using someone's slack name does not work - it must be their slack ID starting with `<@UXXX>`

**Comment by EricRibeiro** [comment]
Sorry for the very late reply. I'm glad the user ID worked for you!

Unfortunately, I could not replicate the issue with the username mention. Since you found a workaround, I'll close this issue, but if the problem surfaces or I can replicate it, I'll be happy to open it again.
