### ISSUE TITLE
How to use custom value from read a json file?

### ISSUE THREAD

**Issue by Norman-else** [CircleCI-Public/slack-orb#356]
## Orb version:

4.10.1

## What happened:

I want to remove the value of `custom` to a json file then read the json file. However, I cannot find a way to config the custom field.

The configuration I have now is:
<img width="745" alt="image" src="https://user-images.githubusercontent.com/19883190/177679964-76050032-199d-420b-a168-64aa3f3decc4.png">
or
<img width="651" alt="image" src="https://user-images.githubusercontent.com/19883190/177680017-216cce77-61e1-4a1a-838f-d08449adb749.png">

But both do not work.

Could someone help me with this issue?

**Comment by EricRibeiro** [comment]
Hi @Norman-else 👋 

To use a file instead of inline JSON, you want to use dynamic templates with the `template` parameter. Have a look here: https://github.com/CircleCI-Public/slack-orb/wiki/Dynamic-Templates.
