### ISSUE TITLE
Slack's use of a tmp directory

### ISSUE THREAD

**Issue by rit001** [CircleCI-Public/slack-orb#357]
The code currently creates a working directory within the user/job space rather than somewhere sensible such as /tmp.

The issue is within line 100, which is a very long bash script which contains "LOG_PATH=\"$(mktemp -d 'slack-orb-logs.XXXXXX')"

I am using that the logic was based on the fact that build agents are considered temporary environments, which are cleared after use - this may not be true for self-hosted runners that can re-use a known file structure. 

At the moment I am having to add additional steps to my config.yml to clear up after the slack orb.

**Comment by EricRibeiro** [comment]
Hi @rit001 👋 

> The issue is within line 100, which is a very long bash script which contains "LOG_PATH="$(mktemp -d 'slack-orb-logs.XXXXXX')"

This directory is created to store logs. It solely exists for troubleshooting. If you don't require them and don't want the folder created, you can set the `debug` parameter to `false`.

**Comment by rit001** [comment]
Any reason why the default for debug is not false?

**Comment by EricRibeiro** [comment]
It wasn't when the parameter was first introduced but the fix was merged in #352 and released on [v4.10.1](https://circleci.com/developer/orbs/orb/circleci/slack?version=4.10.1). Would you mind double-checking your orb version?
