### ISSUE TITLE
Inform user of non-support for Windows environment

### ISSUE THREAD

**Issue by kelvintaywl** [CircleCI-Public/slack-orb#358]
## Orb version:

circleci/slack@4.10.1

## What happened:

Not exactly a bug, but I was thinking it may be good for the `notify` command to fail early if the detected OS is Windows.
Given that we currently do not support Windows in this Orb (see #282), it may be nice to fail with a useful message early then.

**Comment by EricRibeiro** [comment]
Hi @kelvintaywl 👋 

That's a good idea. I'll look into implementing it.

**Comment by kelvintaywl** [comment]
thanks again for this improvement! @EricRibeiro 🙌

**Comment by EricRibeiro** [comment]
Hey, @kelvintaywl 👋 

Support for Windows was implemented in [v4.12.0](https://github.com/CircleCI-Public/slack-orb/releases/tag/v4.12.0). If you want to give it a shot, choose `bash.exe` as your [shell in the Windows executor](https://circleci.com/docs/using-windows/#specifying-a-shell-with-the-windows-executor).

Let me know how it goes!
