### ISSUE TITLE
Conditional fields

### ISSUE THREAD

**Issue by wyardley** [CircleCI-Public/slack-orb#361]
## Describe Request:
Kind of a question, kind of a feature request.
With the old style templates, it was possible to have certain fields only show up if they're set (e.g., mentions). I can't think of a way to do this with the new setup, but is there any way (either using something builtin to Slack templates, or in the orb) to allow us to have a field that will only show up if it's set / used (for example, `mentions`)? Otherwise, the template gets cluttered with fields when they're not in use

## Supporting Documentation Links:

**Comment by KyleTryon** [comment]
I think we could figure out something for this. A "sanitize" function of sorts could take in a template, use JQ to remove keys with empty values, and output the modified config.

**Comment by wyardley** [comment]
That would be amazing. I think the existing custom params wouldn’t work, but that would, possibly.

**Comment by mayank0202** [comment]
Its done now so we can close this i guess @KyleTryon  @wyardley

**Comment by marboledacci** [comment]
Hi @wyardley it's been a while since you first raised this, so I would like to get a bit more information about the scope of this feature.
What kind of fields should be conditional? Could you send and example of what is passed and what should it become?
I understand Kyle idea, but I don't think that's very useful as empty fields on the template would cause an error on the request anyway.

**Comment by wyardley** [comment]
I'm not currently using CircleCI, and it's been like ~ 3 years since this was created, so feel free to close if you'd like. I haven't verified the comment above about this already being done.

The initial description gave one example of a use case that was supported in the past - `@mentions` for example, you might want to have `@mentions` on some slack messages, and not on others (using the same template). I believe there were some other use cases in mind, but it's been a long time since I touched these, so I can't come up with any off the top of my head.

Looks like message and color were also optional in the old version?
https://github.com/CircleCI-Public/slack-orb/tree/v3.4.2
