### ISSUE TITLE
Acknowledging interaction

### ISSUE THREAD

**Issue by kulak91** [CircleCI-Public/slack-orb#366]
## Describe Request:

Hello! I am using slack orb together with my slack bot (based on official slack/bolt app) in the same workspace. When i'm clicking "View Job" button my slack bot also triggers trying to acknowledge the action, this action has no id so i cannot catch it properly.  Would you mind adding static  `callback_id`s, `block_id`s, or `action_id`s  for these basic templates to make it more convenient for use.
(Of course i could use custom templates, but these are fine, just a small upgrade would be amazing)

## Examples:

![image](https://user-images.githubusercontent.com/49899827/197248744-ae94bb17-9879-4241-a796-8f6f4127dd97.png)
![image](https://user-images.githubusercontent.com/49899827/197249683-c5201939-00f5-4066-a75a-d99213c4f0bc.png)

## Supporting Documentation Links:

https://github.com/slackapi/bolt-js/blob/main/docs/_basic/listening_actions.md
https://api.slack.com/legacy/interactive-messages
![image](https://user-images.githubusercontent.com/49899827/197250342-004e3bbf-2d38-44a1-91da-60746fb06c86.png)

**Comment by kulak91** [comment]
https://github.com/CircleCI-Public/slack-orb/pull/367

**Comment by KyleTryon** [comment]
Good call! thank you

**Comment by EricRibeiro** [comment]
Closed in #367. 

While the fix was merged into the main branch, we can't publish a new orb version now. I'll do it as soon as possible next week.

Thanks for your patience!
