### ISSUE TITLE
Create / post to threads

### ISSUE THREAD

**Issue by donnyyung** [CircleCI-Public/slack-orb#378]
## Describe Request:
Hey there,

We post updates for our CICD pipelines to an internal slack channel (ex: when deployments succeed to certain environments, when they require user action, when there are issues, etc.). Which can sometimes make the channels a little noisy.  It would be helpful if in a pipeline we could make our first message a post in the channel and then have all subsequent slack messages be in a thread on that initial message.  I see in the docs it's possible to do this via the API so wanted to see if there were any plans to bring this functionality to the orb.
## Supporting Documentation Links:
https://api.slack.com/messaging/sending#threading

**Comment by tdeekens** [comment]
This sounds super interesting to me. We use the Orb to inform us about daily deployments. It would be super cool to have a parent thread of "Daily deployments" and messages in the thread as what was deployed. 

I would be happy to help with implementation if there is interest and an Orb API agreed upon by us.

**Comment by jr-RXcode** [comment]
Any updates on this. This would be really useful 👍
