### ISSUE TITLE
No notifications sent after upgrading to 4.11.0

### ISSUE THREAD

**Issue by moolitayer** [CircleCI-Public/slack-orb#382]
## Orb version:
Issue happens on both 4.11.0 and 4.12.0

## What happened:
After upgrade from 4.10.0 notifications are no longer sent
*Output:(4.12.0)*
```
#!/bin/bash -eo pipefail
#!/usr/bin/env sh

# Workaround for Windows Support
# For details, see: https://github.com/CircleCI-Public/slack-orb/pull/380
# shellcheck source=/dev/null
eval printf '%s' "$SLACK_SCRIPT_NOTIFY"

Posting Status
BASH_ENV file: /tmp/.bash_env-63bdefd8714ce6519d3b85c7-0-build
Exists. Sourcing into ENV
Checking For JQ + CURL

Exited with code exit status 1

CircleCI received exit code 1
```
(differerent output in 4.11.0 and 4.12.0)

<img width="1761" alt="Screenshot 2023-01-11 at 1 12 50" src="https://user-images.githubusercontent.com/3010449/211681916-06165e87-f548-46bc-97f0-b9c24ce2ced2.png">

## Expected behavior:
Notifications should be sent

## Additional Information:
Our notification sending code:
```
            - slack/notify:
                event: always
                custom: |
                  {
                      "type": "mrkdwn",
                      "text": "$(cat /tmp/msg)"
                  }

```

**Comment by kanocarra** [comment]
I am also seeing the exact same issue, everything was working fine up until I upgraded to `4.12.0`. It tries to send the notification but the fails and then registers that as a fail so stops the execution of any future jobs which is quite detrimental.

our config:
```
            - slack/notify:
                channel: <<parameters.slack_channel>>
                event: pass
                template: DEV_NOTIFICATION
```

And the result:
<img width="742" alt="Screen Shot 2023-01-11 at 3 58 15 PM" src="https://user-images.githubusercontent.com/9301215/211707621-532e0304-eb65-452b-928e-47771a2d53aa.png">

**Comment by moolitayer** [comment]
@EricRibeiro @KyleTryon can someone please take a look?
Any other info needed?

**Comment by KyleTryon** [comment]
Hey folks,

@moolitayer / @kanocarra could we ask you to temporarily add the `debug: true` parameter to the slack notify command and share with us the output?

In version 4.11 we improved how variables are escaped and that was also a step toward 4.12 which also did some refactoring to get the orb to work with windows.

I think this might have to do with environment variable usage.

@kanocarra could you also share the source of your template?

**Comment by moolitayer** [comment]
Hi @KyleTryon, thanks.

This is the setup for the job that uses the orb: 
```
    docker:
      - image: cimg/base:2023.01
    resource_class: small
```
It seems there is no change with the debug parameter:
```
            - slack/notify:
                event: always
                debug: true
                custom: |
                  {
                      "type": "mrkdwn",
                      "text": "$(cat /tmp/msg)"
                  }
```
output:

<img width="840" alt="Screenshot 2023-01-12 at 20 01 58" src="https://user-images.githubusercontent.com/3010449/212144143-98bde2d8-8155-41aa-9acf-7465e4834f4a.png">

**Comment by moolitayer** [comment]
`4.12.1` works for me, thanks for the fix!
