### ISSUE TITLE
Version 4.12.1 Not able to send messages in CircleCI

### ISSUE THREAD

**Issue by Jverrijk** [CircleCI-Public/slack-orb#384]
## Orb version:
4.12.1

## What happened:

Did not send any kind of message. Message is created with the 'Block Kit Builder', but just a simple divider test message is not send. 

## Expected behavior:

A send Fail/Pass message that consist of branch name, County code and some other build information. Plus a link that directs to the reporting CircleCI.

## Additional Information:

In my previous test framework I've used 4.6.3. And that worked just fine. I've tried to figure out what has changed by inspecting the source, but can't find it.
Message example:

```
{
              "blocks": [
                {
                  "type": "divider"
                },
                {
                  "type": "header",
                  "text": {
                    "type": "plain_text",
                    "text": "${CIRCLE_JOB} Succeeded. :white_check_mark:",
                    "emoji": true
                  }
                },
                {
                  "type": "section",
                  "fields": [
                    {
                      "type": "mrkdwn",
                      "text": "*Branch*: ${CIRCLE_BRANCH}"
                    }
                  ]
                },
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "*There is a report ready:*"
                  },
                  "accessory": {
                    "type": "button",
                    "text": {
                      "type": "plain_text",
                      "text": "HTML Report :receipt:",
                      "emoji": true
                    },
                    "value": "Report",
                    "url": "http://www.google.nl",
                    "action_id": "button-action"
                  }
                },
                {
                  "type": "divider"
                }
              ]
            }
```
CircleCI build output:

```
#!/bin/bash -eo pipefail
#!/usr/bin/env sh

# Workaround for Windows Support
# For details, see: https://github.com/CircleCI-Public/slack-orb/pull/380
# shellcheck source=/dev/null
eval printf '%s' "$SLACK_SCRIPT_NOTIFY"

Posting Status
BASH_ENV file: /tmp/.bash_env-63cffc87c2f65065ffa0d05f-0-build
Exists. Sourcing into ENV

Exited with code exit status 1

CircleCI received exit code 1

```

**Comment by andycui66** [comment]
I am experiencing similar issue.  `4.12.1` fails intermittently.
When it fails, I got (some info is masked)
```
#!/bin/bash -eo pipefail
#!/usr/bin/env sh

# Workaround for Windows Support
# For details, see: https://github.com/CircleCI-Public/slack-orb/pull/380
# shellcheck source=/dev/null
eval printf '%s' "$SLACK_SCRIPT_NOTIFY"

Posting Status
BASH_ENV file: /tmp/.bash_env-63d119d1afd56f1c5d40933b-0-build
Exists. Sourcing into ENV
Checking For JQ + CURL
Sanitizing CIRCLE_BUILD_URL...
awk: cmd. line:1: warning: regexp escape sequence `\"' is not a known regexp operator
Sending to Slack Channel: ***********
The message body being sent to Slack can be found below. To view redacted values, rerun the job with SSH and access: slack-orb-logs.C9XX4v/payload.json
{
  "blocks": [
    {
      "type": "header",
      "text": {
        "type": "plain_text",
        "text": ":tada: job has succeeded!",
        "emoji": true
      }
    },
    {
      "type": "actions",
      "elements": [
        {
          "type": "button",
          "text": {
            "type": "plain_text",
            "text": "View Job"
          },
          "url": "***"
        }
      ]
    }
  ],
  "text": "",
  "channel": "***********"
}

Exited with code exit status 6
CircleCI received exit code 6
```

**Comment by nzager** [comment]
Seeing a similar issue, execution seems to run alright but ends with exit code 60 and no messages show up in slack. 

```
Posting Status
BASH_ENV file: <>
Exists. Sourcing into ENV
Checking For JQ + CURL
Sanitizing CIRCLE_USERNAME...
Sending to Slack Channel: <>

Exited with code exit status 60
CircleCI received exit code 60
```

I can't find an exit code 60 listed in source: https://circleci.com/developer/orbs/orb/circleci/slack#orb-source

**Comment by KyleTryon** [comment]
Hey folks, please temporarily roll back your slack version to alleviate the problem. This is likely a an issue with `sed` or `awk` in the `Sanitizing` step which was meant to help with windows/linux cross compatibility.

**Comment by swarajban** [comment]
Which version works?

**Comment by KyleTryon** [comment]
Thank you @swarajban 🎉  I hope this is actually the root of the issue. Would you be able to confirm which image you used before?

**Comment by Nizari** [comment]
```curl: (60) SSL certificate problem: certificate has expired
More details here: http://curl.haxx.se/docs/sslcerts.html

curl performs SSL certificate verification by default, using a "bundle"
 of Certificate Authority (CA) public keys (CA certs). If the default
 bundle file isn't adequate, you can specify an alternate file
 using the --cacert option.
If this HTTPS server uses a certificate signed by a CA represented in
 the bundle, the certificate verification probably failed due to a
 problem with the certificate (it might be expired, or the name might
 not match the domain name in the URL).
If you'd like to turn off curl's verification of the certificate, use
 the -k (or --insecure) option.
 
```

How to solve this issue?

**Comment by KyleTryon** [comment]
@Nizari following the information from @swarajban it seems like it might not be the orb, but the version of curl. Can you share what image you are running the orb in? Could you try updating your image?

**Comment by ZhongRabbit** [comment]
In case this is of help, we're using an old Docker image (not related to the Docker image @swarajban mentioned) for CI/CD for historical reasons. That Docker image also has expired certificates (being addressed).

I wasn't able to use the current latest 4.12.1 due to the issue reported above.

To bypass the certificate verification as well as the issue w/ 4.12.1, I made a custom slack-orb based on the 4.12.0, adding the ability of optional certificate verification. The usage documentation is the same as 4.12.0.

https://github.com/ZhongRabbit/slack-orb-optional-cert
https://circleci.com/developer/orbs/orb/slm-zhong/slack-orb-optional-cert

**Comment by komapotter** [comment]
This error is still occurring.

```
Exited with code exit status 60
CircleCI received exit code 60
```

**Comment by link-komatsu** [comment]
> This error is still occurring.
> 
> ```
> Exited with code exit status 60
> CircleCI received exit code 60
> ```

We too solved the problem by updating the docker base image used by executor.

**Comment by KyleTryon** [comment]
@komapotter please try updating your image. 

I have seen this on MacOS as well, it could be an issue on any OS, but you will need an image that has been updated more recently containing an updated root certificates file that CURL uses to verify SSL certs. When these expire, you will receive SSL errors.

**Comment by KyleTryon** [comment]
Thank you everyone, closing this issue. The solution for those who stumble upon here is:

**Cause:** Your root certificates file has expired in the image or VM you are currently using, which causes CURL to fail with error `60` on SSL requests.

**Solution:** It is recommended to update your image or VM or manually update your root certificates.
