### ISSUE TITLE
Hashicorp image cant work with slack orb

### ISSUE THREAD

**Issue by stascnb** [CircleCI-Public/slack-orb#388]
## Orb version:

circleci/slack@4.12.1

## What happened:

Using hashicorp/terraform:1.1.4 image breaks slack orb,

Spits out this result

```
Posting Status
BASH_ENV file: /tmp/.bash_env-hash-hash-0-build
Does Not Exist. Skipping file execution
Checking For JQ + CURL
SLACK ORB ERROR: CURL is required. Please install.
```
## Expected behavior:

Sending a slack notification

## Additional Information:

Tried using nodejs image as the base and worked fine,

Tried all slack orb versions all the way to 4.10.1 and no luck

**Comment by KyleTryon** [comment]
Hello,
As the error is stating, CURL and JQ are required for this orb to work. Not all images will contain CURL and JQ and may need to be installed or added to the image.
