### ISSUE TITLE
Approve from Slack

### ISSUE THREAD

**Issue by gitphill** [CircleCI-Public/slack-orb#389]
## Describe Request:
Hi 👋 Is it possible to approve from Slack?
## Examples:
Something like [this](https://app.slack.com/block-kit-builder/T07BJB8CR#%7B%22blocks%22:%5B%7B%22type%22:%22section%22,%22text%22:%7B%22type%22:%22mrkdwn%22,%22text%22:%22Awaiting%20approval%20before%20going%20to%20production%20:rocket:%22%7D%7D,%7B%22type%22:%22section%22,%22fields%22:%5B%7B%22type%22:%22mrkdwn%22,%22text%22:%22*Project*:%5Cn$CIRCLE_PROJECT_REPONAME%22%7D,%7B%22type%22:%22mrkdwn%22,%22text%22:%22*Author:*%5Cn$CIRCLE_USERNAME%22%7D%5D,%22accessory%22:%7B%22type%22:%22image%22,%22image_url%22:%22https://assets.brandfolder.com/otz5mn-bw4j2w-6jzqo8/original/circle-logo-badge-black.png%22,%22alt_text%22:%22CircleCI%20logo%22%7D%7D,%7B%22type%22:%22actions%22,%22elements%22:%5B%7B%22type%22:%22button%22,%22text%22:%7B%22type%22:%22plain_text%22,%22emoji%22:true,%22text%22:%22Approve%22%7D,%22style%22:%22primary%22,%22url%22:%22https://circleci.com/api/v2/workflow/$%7BCIRCLE_WORKFLOW_ID%7D/approve/$%7BCIRCLE_WORKFLOW_JOB_ID%7D%22%7D,%7B%22type%22:%22button%22,%22action_id%22:%22basic_on_hold_view%22,%22text%22:%7B%22type%22:%22plain_text%22,%22text%22:%22View%20Workflow%22%7D,%22url%22:%22https://circleci.com/workflow-run/$%7BCIRCLE_WORKFLOW_ID%7D%22%7D%5D%7D%5D%7D)
I'm not sure how auth can work though
## Supporting Documentation Links:
https://circleci.com/docs/api/v2/index.html#operation/approvePendingApprovalJobById

**Comment by KyleTryon** [comment]
Hello,
Not with the current design. There is no way to map users in Slack to permissions on GitHub/CircleCI. The best option is to provide a link in slack, so a user can click it to go through the correct auth flow in the browser.
