### ISSUE TITLE
Build failure

### ISSUE THREAD

**Issue by Ashray-g** [CircleCI-Public/slack-orb#399]
## Orb version:
4.12.1

## What happened:
Build failed (no changes to CircleCI configuration)
<img width="780" alt="Screenshot 2023-03-24 at 14 08 05" src="https://user-images.githubusercontent.com/43589795/227641877-6a8d7ad2-c5ec-4bbb-bc72-36f746ff608c.png">

## Expected behavior:
Build success + notification sent

## Additional Information:
<img width="272" alt="Screenshot 2023-03-24 at 14 08 28" src="https://user-images.githubusercontent.com/43589795/227641971-58f4c21e-bf49-4f88-88c2-5142fffc8bfe.png">
<img width="352" alt="Screenshot 2023-03-24 at 14 08 34" src="https://user-images.githubusercontent.com/43589795/227641996-5ff9a4a3-7037-45c2-b845-f39d32341170.png">
<img width="242" alt="Screenshot 2023-03-24 at 14 08 40" src="https://user-images.githubusercontent.com/43589795/227642016-063ec2ef-1c0c-4643-9794-d0b87ee058fe.png">

**Comment by pieterocp** [comment]
To add to this, also getting this failing when it hits the call to curl inside the method `PostToSlack`. As per google it's likely a curl configuration issue, `Error “curl: (60) SSL certificate problem: unable to get local issuer certificate” can be seen when the SSL certificate on the server is not verified or properly configured`.

And the fact it suddenly went wrong smells like some environment related change.

(It is getting to printing out `Sending to Slack Channel: {channel name}` before exiting with status 60.)

No idea how the underlying curl is configured when running an orb but it might be something some circleci engineer needs to fix, rather than this being something orb side.

**Comment by nanophate** [comment]
> **Cause**: Your root certificates file has expired in the image or VM you are currently using, which causes CURL to fail with error 60 on SSL requests.
>
> **Solution**: It is recommended to update your image or VM or manually update your root certificates.
> https://github.com/CircleCI-Public/slack-orb/issues/384#issuecomment-1476331293

We had similar error on other issue and would be great if the above solution helps. 

I'm seeing this happening to some customer who are using our [legacy deprecated convenience image](https://discuss.circleci.com/t/legacy-convenience-image-deprecation/41034) like `circleci/` which got deprecated and not receiving any updates anymore (includes certificate renewal, security patches). 

I would recommend to check the base image and if there is new release out would recommending trying the newer ones.

**Comment by JuanJo4** [comment]
> I'm seeing this happening to some customer who are using our [legacy deprecated convenience image](https://discuss.circleci.com/t/legacy-convenience-image-deprecation/41034) like `circleci/` which got deprecated and not receiving any updates anymore (includes certificate renewal, security patches).
> 
> I would recommend to check the base image and if there is new release out would recommending trying the newer ones like `cimg/`.

i was having the same issue

```
Exited with code exit status 60
CircleCI received exit code 60
```

but @nanophate recommendation worked, we were using `circleci/` images and migrated to `cimg/` and now is working perfectly.

**Comment by rsmets** [comment]
I just tried changing the orb prefix from `circleci` to `cimg` as recommended by @nanophate and @JuanJo4 but no luck with the Slack orb in particular. It is stating: 

```
Error: Cannot find cimg/slack@4.12.1 in the orb registry. Check that the namespace, orb name and version are correct.
```

Which orbs did you both update to use `cimg`? Looking at the linked forum [post](https://discuss.circleci.com/t/legacy-convenience-image-deprecation/41034) Slack orb is definitely not mentioned. 

Also, please note I documented my own issues with failure to send on `fail` events on [issue 400](https://github.com/CircleCI-Public/slack-orb/issues/400) prior to seeing this one (very poor questionable issue naming choice I must say by @Ashray-g).

**Comment by JuanJo4** [comment]
@rsmets is not the orb prefix, in my case it was the docker image we were using, here is a sample of my `config.yml` file:

```
version: 2.1
orbs:
  slack: circleci/slack@4.12.1
jobs:
  yourjobname:
    docker:
      - image: cimg/python:3.11.2-node
```

you can find the images available here https://circleci.com/developer/images
