### ISSUE TITLE
Unexpected Failures on slack success notify

### ISSUE THREAD

**Issue by andydazzo7** [CircleCI-Public/slack-orb#400]
## Orb version:

4.12.1

## What happened:

My team uses the slack orb to notify when a deployment tool we have runs successfully. Over the weekend, a normally consistently successful notification started to fail to notify our slack channel
<img width="271" alt="Screenshot 2023-04-03 at 2 28 27 PM" src="https://user-images.githubusercontent.com/44784682/229595586-fffc767f-9263-42b6-b999-607c582ab0e7.png">
<img width="498" alt="Screenshot 2023-04-03 at 2 28 49 PM" src="https://user-images.githubusercontent.com/44784682/229595670-47fe0103-1836-444d-88c8-37fefac1e160.png">
The notification uses a custom slack message which I have omitted, but is not causing the error.
The output is as follows: 
![Screenshot 2023-04-03 at 2 29 53 PM](https://user-images.githubusercontent.com/44784682/229595902-cf47ffcc-2086-41d4-b824-be4f4b4c54ad.png)

On normal successes, this is what the output looks like: 
![Screenshot 2023-04-03 at 2 30 27 PM](https://user-images.githubusercontent.com/44784682/229596031-cdd2e21e-ccf8-4b67-91ad-c8640e2280b9.png)

## Expected behavior:

There should be a message sent to my team's slack channel.

**Comment by rsmets** [comment]
I am running into the same issue however only on `fail` events. Below are some screenshots of my CI pipeline with a similar error on the `Slack - Send Notification` job. Running into exit code 60. Using the same, latest Slack orb version, `4.12.1`.

<img width="1274" alt="image" src="https://user-images.githubusercontent.com/2586247/230999816-40995064-3419-4a32-ab93-481d6bcc5970.png">

<img width="202" alt="image" src="https://user-images.githubusercontent.com/2586247/231001679-d8b11fbd-9a2b-4ff0-93a2-c99f976508bc.png">

<img width="302" alt="image" src="https://user-images.githubusercontent.com/2586247/231001745-71c58bc9-f823-46b9-93bd-6b1324c97b0f.png">

**Comment by rsmets** [comment]
Awesome, thank you @KyleTryon for the heads up about #384's comment. Updated the executor and indeed now getting the Slack notifications again.
