### ISSUE TITLE
Mentions not working, behave like a string

### ISSUE THREAD

**Issue by Vanals** [CircleCI-Public/slack-orb#405]
## What happened:

I am adding the orb for slack notification in a second project own by my team, In the first project it works perfectly, in the second one the slack message is triggered but the mention is simply a string.

```
slack_notify: &slack_notify
  event: 'fail'
  channel: '#newskit-all-team'
  mentions: '@newskitdevs'
  branch_pattern: 'main'
```

I am tagging exactly the same group as in the other project, both orb versions are the same, but for some reason the mention is not correct. I have read that you suggest using a UserID, but in my case this is not a user but a slack group.

WHAT HAPPENS ON THE SECOND PROJECT:

<img width="827" alt="Screenshot 2023-05-02 at 12 21 32" src="https://user-images.githubusercontent.com/25549355/235652693-ceb97e58-720a-4853-a4b4-7a96c65373c0.png">

FIRST PROJECT, WHERE WORKS CORRECTLY.
<img width="633" alt="Screenshot 2023-05-02 at 12 24 03" src="https://user-images.githubusercontent.com/25549355/235653160-b1f87ede-020d-4525-b460-ffbc31bb17bc.png">

EDIT: WHAT I HAVE ALSO TRIED

I have even tried with GroupID but doesn't work 

```
slack_notify: &slack_notify
  event: 'fail'
  channel: '#newskit-themes'
  mentions: '<@SUV69PHB2>'
  ```
  
<img width="403" alt="Screenshot 2023-05-02 at 13 44 49" src="https://user-images.githubusercontent.com/25549355/235669741-608052d9-3084-4180-bba7-93ee236547ee.png">

Also tried using the latest version `4.12.3`, but still doesn't work

UPDATE: 🔆🔆🔆🔆

I haven't been able to fix it, but we think the reason for the issue is that the Slack channel is shared between workspaces, so the groups I was trying to tag, not existing in both workspaces, were being printed as a string also where it existed. This is at least what we think, but we can't be sure.

May leave it open in case anyone has another idea or solution. Otherwise close it 👍

## Expected behavior:

Mentions should notify the group, being clickable, and not be a string

**Comment by h-parekh** [comment]
Can confirm this is an issue with `slack: circleci/slack@4.12.5`. Fails to mentioning myself (versus a slack group). Using slack user ID as a workaround for now.

**Comment by CentroDL** [comment]
I'm on `4.12.5`, the following config works for mentions in the success template, but the fail template loses my mention:

<img width="325" alt="image" src="https://github.com/CircleCI-Public/slack-orb/assets/1950229/ab34550a-98ff-479c-b290-fadb1b2c05d7">


Yielding the following messages:

<img width="335" alt="image" src="https://github.com/CircleCI-Public/slack-orb/assets/1950229/08eeac65-61d3-4cc8-b77a-e5d670121325">

**Comment by KyleTryon** [comment]
Hey @Vanals, I have seen this happen before, but I'm not fully sure what causes it. What I can say, is it should work if rather than their name, you use their ID:
https://circleci.com/developer/orbs/orb/circleci/slack#usage-only_notify_on_branch

```
     - slack/notify:
          branch_pattern: production
          event: fail
          mentions: <@U8XXXXXXX>, @UserName
          template: basic_fail_1
```

You can get a users ID from their profile, click the three dots and it will have a menu item to copy it.

**Comment by Navusas** [comment]
Same problem here. 

Tried:
```
      - slack/on-hold:
          mentions: <@S0S4XXXXH>
          context: ....
```
and
```
      - slack/on-hold:
          mentions: @TeamName
          context: ....
```
and
```
      - slack/on-hold:
          mentions: '<@S0S4XXXXH>'
          context: ....
```

Nothing works. The end result is the same:
![image](https://github.com/CircleCI-Public/slack-orb/assets/32360417/7a0c8e29-2c9f-4cec-96ae-f6d47ac55283)

**Comment by marboledacci** [comment]
Do these mentions work when you use them manually in the target slack channel?

**Comment by Navusas** [comment]
Sorry this is no longer relevant to me and I can't test it anymore. Others might still have some input.
