### ISSUE TITLE
Slack notification fails when apostrophe is used in commit message

### ISSUE THREAD

**Issue by fsintegrations** [CircleCI-Public/slack-orb#424]
## Orb version:
4.12.0

## What happened:

Orb crashes with error  `unexpected EOF while looking for matching `''` 
when the commit message or PR title contains an apostrophe

## Expected behavior:
Slack notification should works fine even with apostrophe in message content

## Additional Information:
Commit message that crashed the slack notification `Adding flow to allowed attributes so that it's not skipped.`
![image](https://github.com/CircleCI-Public/slack-orb/assets/46435009/4ba33bff-163d-4a65-b7e2-e3ec80faa4ff)

I could see this issue is already in closed state but we still face this issue if the commit message or PR title contains apostrophe (')
https://github.com/CircleCI-Public/slack-orb/issues/186
https://github.com/CircleCI-Public/slack-orb/pull/198

**Comment by marboledacci** [comment]
@fsintegrations I'm not very familiar with the historic of this issue, can you provide more details on how you are using the orb? I was trying to replicate with newer version using apostrophe everywhere and didn't get any error.
