### ISSUE TITLE
Notifications are failing because of Slack Rate Limit with no Workaround.

### ISSUE THREAD

**Issue by scott-hill-alkami** [CircleCI-Public/slack-orb#426]
## Orb version:

slack: circleci/slack@4.5.0

## What happened:

CircleCI jobs are failing the **Slack - Sending Notification** step

CircleCI build:  https://app.circleci.com/pipelines/github/Alkami/configuration-utility/14481/workflows/3b13f8db-c6e2-4ff6-841c-5f77e14e72ff/jobs/14291
 
**Slack - Sending Notification**
Posting Status
Checking For JQ + CURL: Debian
Sending to Slack Channel: mobile-status
Exited with code exit status 22

I'm seeing this message in our Slack channel as well:
Due to a high volume of activity, we are not displaying some messages sent by this application. • [Details](https://api.slack.com/docs/rate-limits)

## Expected behavior:

Successfully send the message, maybe retry after a second or two?

## Additional Information:

There is currently no workaround or this failure.  Once the Rate Limit is hit all notifications fail.
We need a retry loop here with a parameter to set the number of retries... maybe default to 0
An onion to set the seconds-to-wait-between-retries as well would be nice.

**Comment by marboledacci** [comment]
There is a retry option now in version 5.1.0
