### ISSUE TITLE
Orb should work even if the default shell is not bash

### ISSUE THREAD

**Issue by martin-displayr** [CircleCI-Public/slack-orb#429]
## Orb version:

`4.12.5`

## What happened:

When using a Windows runner and Powershell as the shell for the job, the orb fails:

```
eval : The term 'eval' is not recognized as the name of a cmdlet, function, script file, or operable program. Check 
the spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:6 char:1
+ eval printf '%s' "$SLACK_SCRIPT_NOTIFY"
+ ~~~~
    + CategoryInfo          : ObjectNotFound: (eval:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
 

Exited with code exit status 1
```

## Expected behavior:

You can use any shell at the job level, and the orb just works.

I think this should be possible, the orb just needs to specify to run it's commands using bash.exe ?

## Additional Information:

Workaround for me is to set the job level shell to bash, then override to powershell for every job. This works in a Windows runner.

Related: https://github.com/CircleCI-Public/slack-orb/pull/380#issuecomment-1778648385

**Comment by KyleTryon** [comment]
Hey, I just wanted to share here that we are nearly about to release the beta version of a re-write of this orb in Go. I'll post here again with information for upgrading to the beta test. `eval` is no longer supported in the go version, so this should be resolved. The only hard requirement we believe will be needed is either CURL or WGET

**Comment by RobotRogue** [comment]
I have no way to test this, but would specifying that the commands be run against bash in the `notify.yml` file work?

`steps:
  - run:
      when: on_fail
      name: Slack - Detecting Job Status (FAIL)
      shell: bash
      command: |
        echo 'export CCI_STATUS="fail"' > /tmp/SLACK_JOB_STATUS
  - run:
      when: on_success
      name: Slack - Detecting Job Status (PASS)
      shell: bash
      command: |
        echo 'export CCI_STATUS="pass"' > /tmp/SLACK_JOB_STATUS
  - when:
      condition:
        not:
          equal: [ "", <<parameters.thread_id>> ]
      steps:
        - restore_cache:
            keys:
              - cache-<< parameters.thread_id >>-{{ .Environment.CIRCLE_PIPELINE_ID }}
            when: always
  - run:
      when: always
      name: << parameters.step_name >>
      shell: bash
      environment:
        SLACK_PARAM_EVENT: "<<parameters.event>>"`

**Comment by marboledacci** [comment]
The development of the go version for this orb is now on stand by, but I'm addressing this issue in the next release. The orb will enforce the usage of bash, no matter the shell on the executor.

**Comment by marboledacci** [comment]
The version [4.14.0](https://circleci.com/developer/orbs/orb/circleci/slack?version=4.14.0) of the orb is now using bash only to run the scripts.

**Comment by gavinclarkeuk** [comment]
Switching to bash breaks any use of the orb on alpine based images, as they don't include bash by default.

**Comment by marboledacci** [comment]
Hi @gavinclarkeuk we're starting to standardize the orbs to use bash only, I'll add more information on the orb version to let this constraint clear. 
This orb still supports alpine, but only with bash. You can install bash directly or use an alpine based image that comes with bash.

**Comment by gavinclarkeuk** [comment]
@marboledacci thats fine, but as it is clearly a breaking change shouldn't it have been a major release, in keeping with semver conventions?

**Comment by marboledacci** [comment]
@gavinclarkeuk thanks for the heads up, you are totally right, we hadn't considered this to be a breaking change at the beginning. We'll be removing the bash change in a new minor version, and then redeploy it as a major.

**Comment by kubosho** [comment]
> This orb still supports alpine, but only with bash. You can install bash directly or use an alpine based image that comes with bash.

If the docker image of an executor that uses `slack-orb` is based on alpine, does that mean I have to work to install bash on all of them?
