### ISSUE TITLE
CircleCI logo image is not getting displayed

### ISSUE THREAD

**Issue by mayank0202** [CircleCI-Public/slack-orb#442]
## Orb version:

`circleci/slack@4.1`

## What happened:

success_tagged_deploy_1   background circleCi image is not coming now 
screenshot: 
<img width="1040" alt="circleci-bug" src="https://github.com/CircleCI-Public/slack-orb/assets/83959396/51690215-2568-428b-9489-1d1ba4ce1871">

## Expected behavior:

It should display circleCi logo image

**Comment by ls-philippe-casgrain** [comment]
Also happens with circleci/slack@4.12.5 (latest release as of this comment)

**Comment by ls-philippe-casgrain** [comment]
Ah, looks like we get an "access denied" for the image resource 
![image resource](https://assets.brandfolder.com/otz5mn-bw4j2w-6jzqo8/original/circle-logo-badge-black.png)

**Comment by ls-philippe-casgrain** [comment]
That's 
`https://assets.brandfolder.com/otz5mn-bw4j2w-6jzqo8/original/circle-logo-badge-black.png` if you are keeping track

**Comment by pieterocp** [comment]
Looks like circleci/slack@4.12.6 fixes it, see #444

**Comment by ls-philippe-casgrain** [comment]
Can confirm that for us, updating to 4.12.6 fixes the issue.

**Comment by mayank0202** [comment]
yes it worked for me thanks everyone
