### ISSUE TITLE
slack/on-hold doesn't seem to support the thread_id parameter.

### ISSUE THREAD

**Issue by DavidWeng916** [CircleCI-Public/slack-orb#451]
## Describe Request:
Hi, @jasonyoung-pearl. when I use `slack/on-hold` I realize that there is no `thread_id` parameter to use. Is there any other way to bring in `thread_id`?

## Examples:
 - slack/on-hold:
          context: slack-secrets
          thread_id: XXXX <--- need this parameter

## Supporting Documentation Links:

**Comment by jasonyoung-pearl** [comment]
@DavidWeng916 sorry, I'm not a maintainer of this orb. I only opened a PR to address a specific issue. I'd recommend reaching out to CircleCI support.

**Comment by marboledacci** [comment]
[Version 4.14.0](https://circleci.com/developer/orbs/orb/circleci/slack?version=4.14.0) now supports this. I'm closing the issue.
