### ISSUE TITLE
Issue with Passing Formatted JSON as a Custom Message in slack/notify

### ISSUE THREAD

**Issue by mkoiev** [CircleCI-Public/slack-orb#468]
### Steps to reproduce

1. Generate a JSON payload in a Node.js script (generate-slack-message.js) using:
```
 const payload = {
    blocks: [
        {
            type: "section",
            text: {
                type: "plain_text",
                text: "Your Slack message here",
            },
        },
    ],
};
console.log(JSON.stringify(payload)); // Outputs JSON
```

2. Read this JSON output and format it in the CircleCI config.yml file with jq to ensure compactness and proper formatting.
3. Pass the formatted JSON to slack/notify via the custom parameter.

### Variants Attempted

**Variant 1**: Direct Command Substitution in YAML (Did not work)

We tried directly passing the output of cat in the custom field:

`custom: $(cat slack-message.txt | jq -c .)`

**Variant 2**: Use of BASH_ENV for Temporary Storage (Did not work)

Next, we tried exporting the JSON payload to a temporary .env file using BASH_ENV, with the following steps in config.yml:
```

- run:
    name: Generate and Export Slack Message
    command: |
      export SLACK_MESSAGE=$(node .circleci/scripts/generate-slack-message.js | jq -c .)
      echo "export SLACK_MESSAGE='$SLACK_MESSAGE'" >> $BASH_ENV
- slack/notify:
    custom: "$SLACK_MESSAGE"

```
Variant 3: Saving JSON to a File and Loading with source
We attempted to save the JSON output to .env_tmp and load it in the next step:

```
- run:
    name: Generate JSON and Save to .env_tmp
    command: |
      SLACK_MESSAGE=$(node .circleci/scripts/generate-slack-message.js | jq -c .)
      echo "export SLACK_MESSAGE='$SLACK_MESSAGE'" > .env_tmp
      source .env_tmp
- slack/notify:
    custom: "$SLACK_MESSAGE"
```

### Expected result

The custom parameter in slack/notify should receive the JSON-formatted payload stored in SLACK_MESSAGE and pass it to Slack as intended.

### Actual Result
None of the methods successfully transmitted the JSON payload in the expected format to the custom parameter in slack/notify.

### Additional Notes
This issue has caused difficulty in achieving our automated notification requirements. It appears that CircleCI YAML configuration does not fully support command substitution or intermediate JSON processing, which is necessary for formatting and transmitting JSON-based Slack messages.

During troubleshooting, we observed that directly embedding the JSON object in the custom field worked perfectly. For example:
`custom: |
  {
    "blocks": [
      {
        "type": "section",
        "text": {
          "type": "plain_text",
          "text": "Your Slack message here"
        }
      }
    ]
  }
`
Using this method, the message was sent successfully to Slack without any parsing errors.

However, when attempting to pass the same JSON object as a variable (using the methods described above), we consistently encountered parsing errors. This suggests that the parsing issue only arises when the JSON is stored in a variable and then passed to custom, rather than being hardcoded directly.

Could the team provide guidance on a reliable method to format and pass JSON data to slack/notify, or consider adding support for JSON handling within CircleCI YAML?

**Comment by marboledacci** [comment]
Hi @mkoiev, by default the parameters of an orb are always strings and they are not evaluated in any way. We evaluate these values when is common for users to get the value from an environment variable.
Fortunately, adding this is not complex so I'll create a PR and add this.

**Comment by mkoiev** [comment]
@marboledacci that's absolutely what do I need, thank you a lot. Now I can dynamically setup slack message using JS script. Thank you a lot for such fast fix.
For those who may have same needs i do follow


funtion genereateSlackMessage() {
// do some logic
const message = {blocks: {}}
return  message
}

const payload =  genereateSlackMessage()
fs.writeFileSync('slack-message.json', JSON.stringify(payload))


in config.yml

          steps:
            - run:
                name: Generate Slack Notification
                command: node .circleci/scripts/generate-slack-message.js
                when: always
            - run:
                name: Export Slack Message to Environment
                command: echo 'export SLACK_MESSAGE=$(cat slack-message.json)' >> $BASH_ENV
                when: always
            - slack/notify:
                custom: $SLACK_MESSAGE
