### ISSUE TITLE
mentions don't work with user groups

### ISSUE THREAD

**Issue by iynere** [CircleCI-Public/slack-orb#5]
currently, mentions only work with individual users' UUIDs. User Group UUIDs do not resolve to a correctly formatted @mention after passing through the Slack API.

**hypothesis:**
- all users' UUIDs start with U, whereas all User Group UUIDs start with S
- in which case, we will have to build out some shell scripting to check if a mention is an individual or a User Group, and, if a user group, query the Slack API to get all its members and add them to the list of mentions

**Comment by KyleTryon** [comment]
Mentions for group users added. You may now enter the group subteam ID in the mentions list.
https://github.com/CircleCI-Public/slack-orb/pull/8
