### ISSUE TITLE
Support for changed build statuses

### ISSUE THREAD

**Issue by danpalmer** [CircleCI-Public/slack-orb#54]
### Feature request

We do many builds a day, and use Slack for visibility on the status of those builds. A message every time the build succeeds is not particularly useful information, as this is the default, and the significant majority of our builds succeed. Generally, we want notifications for:

- Build failures
- A build success the first time after a failure

The former tells us we need to go and fix something, and continued notifications of failures make it less likely that it will be forgotten. The latter notifies those who may be interested in the project, but not involved in the fixing of the build, that everything is ok once again.

It would be great to have the notion of whether the build status has _changed_ from the last run, to enable workflows like this.

**Comment by KyleTryon** [comment]
Hello @danpalmer 

Notifications on failures only is already possible via the "fail_only" env var under the Status command: https://github.com/CircleCI-Public/slack-orb#status

As for notifications based on the success or failure of the last run job, this is not yet possible but something we'd like to add to the Slack Orb when possible. API updates in the future to CircleCI may allow this functionality.

**Comment by danpalmer** [comment]
@KyleTryon thanks for the response. I've seen the `fail_only` parameter, that's great and I expect we'll use that, but it really is the change in build status that we're looking for.

**Comment by iynere** [comment]
@danpalmer @KyleTryon this _should_ already be possible with our current API, as we have a job status that is `fixed`, which is automatically given to the first green build after a red build, i believe

@danpalmer feel free to take a stab at a PR, & thank you !

**Comment by ide** [comment]
I implemented this behavior in a pair of custom orb. The way it works is the first orb tracks edge triggers between builds: https://circleci.com/orbs/registry/orb/expo/job-status-change. It assumes you're using bash and writes an environment variable named `CIRCLE_JOB_STATUS_CHANGE` to `$BASH_ENV`. `$CIRCLE_JOB_STATUS_CHANGE` can be "success", "failed", or one of the edge triggers, "fixed" and "broke". This orb is fairly flexible and you might be able to use it in your own jobs.

A second orb uses this status change to decide how and whether to notify Slack: https://circleci.com/orbs/registry/orb/expo/slack-job-status-notification. It reads `$CIRCLE_JOB_STATUS_CHANGE` by default but you also can explicitly pass in a status change via a parameter. Also it notifies only on edge triggers, not continuous failures. This orb isn't intended to be flexible and you probably should write your own.

Both orbs are MIT-licensed so copy & paste whatever you'd like.

**Comment by MetalDent** [comment]
Hi, anyone is working on this issue?

**Comment by imnotjames** [comment]
I'm taking a look at this as I'd like this feature..

**Comment by imnotjames** [comment]
Hi friends!  I've taken a crack at adding the feature to this orb.  I've added the `change_only` parameter which causes success messages to only get fired off with `fixed` and failure messages to only get fired off with `broke`.

**Comment by dlopuch** [comment]
+1

This is a much needed regression from the previous built-in chat notifications which had the "Fixed/Failed Only" option. 

Slack-bots in general are very noisy and distracting. In the case of my CI, I don't need to get a context-switching ping on every successful build... I just need to know when something is broken, when it continues to be broken, and then when it stops being broken. 

Truly effective developer tools help get the job done then fade into the background.
