### ISSUE TITLE
Documentation for approval command

### ISSUE THREAD

**Issue by Supernats** [CircleCI-Public/slack-orb#56]
### Orb version
2.5.0

This is not a bug report as much as a feature request. I found the `approval` command in the source, but not the documentation.

**Comment by iynere** [comment]
@Supernats we probably shouldn't be in the habit of duplicating everything from the orb source in the README file—if you take a look at some of our other orb repos, it's rare for them to have this much redundancy—it's not scalable to keep that much info accurate across 2 locations, for so many repositories. & the source code is designed to be self-documenting. that said, if there's something that's unclear even after looking at the documentation on the orb registry page, please feel free to submit a PR to this repo to add additional info to the README—thanks !!

**Comment by Supernats** [comment]
I would argue that having _some_ of the commands documented leads one to believe _all_ will be documented. I think your position would be more defensible if the documentation for the other two commands were removed.

**Comment by iynere** [comment]
@Supernats i agree with you—we should remove that documentation. feel free to submit a PR for that, otherwise we will get to that at some point soon.

**Comment by iynere** [comment]
most of our repos' readmes look like this, which i think is ideal:

https://github.com/circleci-public/docker-orb#usage

& then all you need to add are any additional usage notes that might not be clear from the self-documentation in the orb source

**Comment by Supernats** [comment]
Yeah, that's more than enough. Saying what's there is the biggest piece. I'll ping you on the PR if I get to it.

**Comment by KyleTryon** [comment]
I will add these docs were originally created before we had the orb registry (self-documenting). At minimum, I would say keeping the preview images are what I would be most concerned about as we have no other way of showing that.
