### ISSUE TITLE
Have a newly Fixed status 

### ISSUE THREAD

**Issue by matspitz1** [CircleCI-Public/slack-orb#63]
### Orb version
3.2

### What happened
I am using circleci/slack@3.2.0. I want to be notified by slack for failures & fixed builds only. However it seems like there is only a parameter/command for failed_only builds.

### Expected behavior
This seems to be an option through the CircleCI chat notification settings but not through the Orb. How can i get slack notification through the orb for Failed and Fixed but no regular success?

**Comment by KyleTryon** [comment]
Hello,

"Fixed" is not currently a status provided from CircleCI. The Slack Orb is unaware of the status of any job or workflow that took place before the Orb has ran. The integrated chat feature shown in the CircleCI UI is in reference to CircleCI 1.0 (many server users are still on 1.0) which was not workflow aware and only worked for single jobs on 1.0

This functionality may become possible with the new Pipelines API to be released soon. At this time if possible we would like to add this functionality.

**Comment by deeTEEcee** [comment]
why not keep the ticket open?

for reference just to link things: https://discuss.circleci.com/t/can-the-slack-orb-only-notify-on-failure-or-is-fixed-an-option/30690/2

**Comment by Wambosa** [comment]
This just stung us today. This used to be a work-out-of-the-box feature, but now requires some additional setup or state tracking on our own for the "fixed" build. Its too bad this orb version does not have the same feature parity as the 1.0 version.
Is there a way to opt out of the new ui and use the previous setup? Our old projects still work, but new ones lose the "fixed" notification.

I am referencing the docs here, and the new UI which now lacks the test-integration button and only failed/fixed toggle.
https://circleci.com/orbs/registry/orb/circleci/slack#commands-status

**Comment by jarekwg** [comment]
Any news in this space w.r.t 4.x orb?
