### ISSUE TITLE
[Question]  Is it easy to check source code changes and CircleCI Orb Registry releases?

### ISSUE THREAD

**Issue by paveg** [CircleCI-Public/slack-orb#69]
### Orb version
- 3.2.0 or higher

### What happened

It is a question.
Although I usually use slack-orb in production code,
it is difficult to confirm the changes because there is a fatal difference between the version described in orbs and the version control of the source code.

Do you think about measures?

### Expected behavior

I hope to be able to easily see the source code and changes in the CircleCI orb registry.
For example, unify the release version of GitHub Repository and the version of CircleCI Orb Registry.

**Comment by iynere** [comment]
@paveg very good question !

the source code on the `master` branch here should always reflect the latest version in the orb registry.

we totally agree about synchronizing github releases with orb registry versions ! we have an incomplete solution so far, but we're working on it.

let me look @ the slack code here & see if there's any easy ways we can improve things, as well

**Comment by iynere** [comment]
@paveg i'll leave this issue open for now, b/c https://github.com/CircleCI-Public/slack-orb/pull/70 / https://github.com/CircleCI-Public/slack-orb/pull/71 isn't a _complete_ solution, but it will help a lot, i think

**Comment by paveg** [comment]
@iynere thanks for answering, I'll waiting for correction is reflected.

**Comment by KyleTryon** [comment]
Previous version of source code can now be viewed directly on the CircleCI registry.
