### ISSUE TITLE
Include custom variables in slack message

### ISSUE THREAD

**Issue by alan-parry** [CircleCI-Public/slack-orb#76]
### Orb version

3.3.0

### What happened
I'm trying to include custom variables which are established earlier in my build in the slack message.  To pass these between previous steps I do

echo "export GIT_COMMIT_MESSAGE=$GIT_COMMIT_MESSAGE" >> variables/var.sh

then for steps where I require these I first do:

source ~/work/variables/var.sh

This works fine but I don't see a way to bring these in to my slack orb steps. Is there a fix or a workaround you can suggest? Thanks!

- slack/notify:
          color: '#2eb886'
          mentions: 'U7J9RP44GH' #Me
          message: Built and pushed $MY_CONTAINER\n$GIT_COMMIT_MESSAGE\n
          webhook: https://hooks.slack.com/services/etc/etc

### Expected behavior

My message should include the variable values, instead they are blank.

**Comment by alan-parry** [comment]
I resolved this by adding variables to the BASH_ENV

**Comment by emma-sax4** [comment]
Can you post the final code that you used to add the values to the `$BASH_ENV`?

**Comment by iamtgray** [comment]
Also want to know how to do this if possible? @alan-parry

**Comment by emma-sax4** [comment]
@iamtgray I ended up finding this solution:
https://github.com/emma-sax4/emma-sax4.github.io/blob/release/.circleci/generate-slack-message.sh#L17-L18
https://github.com/emma-sax4/emma-sax4.github.io/blob/release/.circleci/config.yml#L45

So this works nicely.

**Comment by victorboissiere** [comment]
The URLs are not working anymore.
I used something like this:
```bash
echo "export BUILD_OUTPUT_MESSAGE='My custom variable to use in Slack orbs'" >> $BASH_ENV
```

**Comment by emmasax4** [comment]
@victorboissiere I've updated the URLs in the comment above. Sorry about that. I try not to link to things directly on a branch, but rather on a SHA commit so the URLs persist.

**Comment by NenadJovicic** [comment]
Still don't see how to include actual commit message, and not SHA of commit
because it is useful to see actual commit message. No one knows commit SHA :smile:

**Comment by KyleTryon** [comment]
@NenadJovicic Here's a cheat to get the commit message:

```
echo "export COMMIT_MESSAGE=\"$(git log --format=oneline -n 1 $CIRCLE_SHA1)\"" >> $BASH_ENV
```

source: https://discuss.circleci.com/t/git-commit-message-in-environment-variable/533/13

**Comment by NenadJovicic** [comment]
@KyleTryon yup, found it exactly there after asking question here :smile: 
thanks
