### ISSUE TITLE
Changing SLACK_WEBHOOK parameter type to env_var_name

### ISSUE THREAD

**Issue by pbaderia01** [CircleCI-Public/slack-orb#79]
### Orb version
8.7.23

### What happened
We should consider changing the data type of slack webhook to `env_var_name` since the variable does not require user input once set and would be easy to manage using CircleCI env vars. Also this follows the best practices for orbs.

https://circleci.com/docs/2.0/orbs-best-practices/#parameters

**Comment by piyush-insider** [comment]
Hi, I would also like to pick this up. Please consider adding the `orbtoberfest` label on the issue.
