### ISSUE TITLE
When you will release the PR #67?

### ISSUE THREAD

**Issue by teroids** [CircleCI-Public/slack-orb#97]
Hey guys! 
I am working with the Slack Orb and it is amazing.

I would like to use the parameter `channel` but the last version of Slack Orb in Circle CI does not allow me to use it :c 
Just wondering when the feature will be available?

Thank you !

**Comment by KyleTryon** [comment]
A new version of the Slack orb has been published. 3.4 can be found here: https://circleci.com/orbs/registry/orb/circleci/slack#commands-approval
